-- =====================================================================
-- संयोजन विश्लेषण — complete Graha + Bhava Faladesh (part C)
-- Adds bhavas 2,3,4,5,6,8,9,11,12 for grahas 7-9 (Shani, Rahu, Ketu).
-- Existing rows for bhavas 1,7,10 are kept (INSERT IGNORE is idempotent).
-- Content: structured knowledge data, written in own words.
-- =====================================================================

USE vedic_astrology_learn;

INSERT IGNORE INTO `graha_bhava` (`graha_id`,`bhava_id`,`interpretation_np`,`interpretation_en`,`positive_effects`,`challenges`,`career_indication`,`financial_indication`,`relationship_indication`,`classical_interpretation`,`sanskrit_reference`,`remedies`) VALUES

(7,2,
'शनि दोस्रो भावमा परिश्रमबाट कमाएको धन दिन्छ। बचत ढिलाइपछि हुन्छ तर स्थिर हुन्छ। वाणी गम्भीर र कडा हुन्छ, परिवारमा जिम्मेवारी र संयमको वातावरण रहन्छ।',
'Saturn in the second gives wealth earned through labour. Savings come late but stay stable. Speech is grave and stern, and the family atmosphere keeps responsibility and restraint.',
'दिगो बचत, परिश्रम धन, जिम्मेवारी, संयम',
'वाणी कडापन, धनमा ढिलाइ, परिवारमा कठोरता',
'खनन, कृषि, लेखा, श्रम सम्बन्ध',
'ढिलो तर स्थिर सम्पत्ति, मुद्रा बचत',
'परिवारमा गम्भीर तर जिम्मेवार व्यवहार',
'द्वितीयस्थो शनिर्धनवान् भवति',
'Phaladeepika',
'शनिवार तिल तेल दान र शनि मन्त्र जप।'),

(7,3,
'शनि तेस्रो भावमा ढिलो तर दृढ साहस दिन्छ। भाइबहिनीप्रति कर्तव्यपरायणता रहन्छ। छोटो यात्रामा विलम्ब हुन सक्छ तर परिश्रमले काम पूरा गर्छ।',
'Saturn in the third gives slow but firm courage. Duty bound attitude remains towards siblings. Short journeys may be delayed though labour completes the work.',
'दृढ साहस, कर्तव्यपरायणता, परिश्रम, धैर्य',
'यात्रा विलम्ब, भाइबहिनीसँग दूरी, उदासी',
'खनन, श्रम, प्रशासन, लेखन',
'परिश्रमबाट ढिलो तर निश्चित आय',
'भाइबहिनीसँग कर्तव्य सम्बन्ध',
'तृतीयस्थो शनिर्धैर्यवान् भवति',
'Brihat Jataka',
'शनिवार शनि मन्त्र जप र काला तिल दान।'),

(7,4,
'शनि चौथो भावमा घर र सुखमा ढिलाइ ल्याउँछ। जग्गा-घर पछि मिल्छ, माता दीर्घायु हुन्छन् तर भावनात्मक शान्ति ढिलो मिल्छ। सादा र अनुशासित घर वातावरण रहन्छ।',
'Saturn in the fourth brings delay in home and comforts. Land and house come later, the mother lives long though emotional peace arrives late. A simple and disciplined home environment persists.',
'जग्गा-घर (ढिलाइपछि), माता आयु, अनुशासन, सादगी',
'सुख ढिलाइ, भावनात्मक एकान्तता, घर तनाव',
'भवन निर्माण, कृषि, भण्डार, प्रशासन',
'जग्गाबाट ढिलो तर दिगो लाभ',
'परिवारमा सादा र गम्भीर सम्बन्ध',
'चतुर्थस्थो शनिर्गृहं ददाति',
'Saravali',
'शनिवार तिल तेल दान र शिवलिङ्गमा जल।'),

(7,5,
'शनि पाँचौं भावमा गम्भीर बुद्धि र पुरानो कर्मको फल दिन्छ। सन्तानमा ढिलाइ हुन सक्छ तर पछि सुख मिल्छ। विद्यामा धैर्य र गहिरो अध्ययनले सफलता दिलाउँछ।',
'Saturn in the fifth gives a serious intellect and the fruit of past karma. There may be delay in children though happiness follows later. Patency in study and deep learning bring success.',
'गम्भीर बुद्धि, गहिरो अध्ययन, पुरानो पुण्य फल, धैर्य',
'सन्तान ढिलाइ, उदासी, अति गम्भीरता',
'अनुसन्धान, शिक्षण, ज्योतिष, खनन',
'पुरानो लगानीबाट फल, तर ढिलो',
'सन्तानसँग गम्भीर तर स्थिर सम्बन्ध',
'पञ्चमस्थो शनिर्मेधावी भवति',
'Brihat Parashara Hora Shastra',
'शनिवार शनि मन्त्र जप र विद्यार्थीलाई दान।'),

(7,6,
'शनि छैटौं भावमा धैर्य र संयमले शत्रुलाई परास्त गर्छ। सेवा र श्रममा प्रतिष्ठा मिल्छ। दीर्घ रोग हुन सक्छ तर उपचार र अनुशासनले जित्छ।',
'Saturn in the sixth defeats enemies through patience and restraint. Respect comes in service and labour. Long lasting illness may occur though treatment and discipline win.',
'शत्रु पराजय, सेवा प्रतिष्ठा, धैर्य, ऋण मुक्ति',
'दीर्घ रोग, थकान, कानुनी विवाद',
'सेवा, खनन, प्रशासन, चिकित्सा',
'ऋण ढिलो तर फिर्ता, श्रमबाट आय',
'शत्रुसँग लामो संघर्षपछि विजय',
'षष्ठस्थो शनिर्रिपुं नाशयति',
'Phaladeepika',
'शनिवार तिल तेल दान र शनि मन्त्र जप।'),

(7,8,
'शनि आउठौं भावमा दीर्घायु र गहिरो अनुसन्धान दिन्छ। विरासत र परिवर्तनमा ढिलाइ हुन्छ। दीर्घ रोग र कठिन अनुभव हुन सक्छ तर अन्ततः जीवन बच्छ र रहस्य ज्ञान प्राप्त हुन्छ।',
'Saturn in the eighth gives longevity and deep research. Delay occurs in inheritance and transformation. Long illness and hard experiences may come though life is ultimately preserved and knowledge of mysteries is gained.',
'दीर्घायु, गहिरो अनुसन्धान, विरासत (ढिलो), रहस्य ज्ञान',
'दीर्घ रोग, विरासत विवाद, कठिन परिवर्तन',
'अनुसन्धान, ज्योतिष, चिकित्सा, खनन',
'विरासत ढिलो तर मिल्छ, बचत दिगो',
'गोपनीयता, जीवनसाथीसँग गम्भीरता',
'अष्टमस्थो शनिरायुर्दायी भवति',
'Brihat Jataka',
'शनिवार तिल तेल दान र शिव मन्त्र जप।'),

(7,9,
'शनि नवौं भावमा भाग्य र धर्ममा ढिलाइ तर दिगोता ल्याउँछ। पिता र गुरुबाट कर्तव्य र अनुशासन सिकिन्छ। पछि भाग्योदय हुन्छ र धर्ममा ख्याति मिल्छ।',
'Saturn in the ninth brings delay but stability in fortune and dharma. Duty and discipline are learned from father and teacher. Fortune rises later and fame is gained in dharma.',
'भाग्योदय (ढिलो), अनुशासन, गुरु ज्ञान, दिगो धर्म',
'भाग्य ढिलाइ, पितासँग दूरी, यात्रा विलम्ब',
'शिक्षण, प्रशासन, धर्म सेवा, खनन',
'पछि भाग्यबाट स्थिर सम्पत्ति',
'गुरु र पिताप्रति कर्तव्य सम्बन्ध',
'नवमस्थो शनिर्भाग्यवान् भवति',
'Saravali',
'शनिवार शनि मन्त्र जप र गुरु पूजा।'),

(7,11,
'शनि एघारौं भावमा कडा परिश्रमपछिको स्थिर लाभ दिन्छ। इच्छा ढिले तर पूरा हुन्छन्। वयोवृद्ह र अनुभवी मित्रहरूबाट सहयोग मिल्छ र आय स्थिर हुन्छ।',
'Saturn in the eleventh gives steady gain after hard labour. Desires are fulfilled late. Support comes from elder and experienced friends and income becomes stable.',
'स्थिर लाभ, इच्छा पूर्ति, अनुभवी मित्र, दिगो आय',
'लाभ ढिलाइ, मित्र कम, अति बचत',
'प्रशासन, खनन, कृषि, दीर्घकालीन निवेश',
'ढिलो तर सुनिश्चित आय र पेन्सन',
'वयोवृद्ह मित्रसँग गम्भीर सम्बन्ध',
'एकादशस्थो शनिर्लाभं ददाति',
'Phaladeepika',
'शनिवार तिल तेल दान र वृद्ध सेवा।'),

(7,12,
'शनि बाह्रौं भावमा संयमित खर्च र एकान्तमा शान्ति दिन्छ। विदेश वास र परदेशमा परिश्रम हुन्छ। खर्च नियन्त्रणमा रहन्छ तर निद्रा र एकान्ततामा समस्या हुन सक्छ।',
'Saturn in the twelfth gives controlled expenditure and peace in isolation. There is labour in foreign residence. Spending stays controlled though sleep and loneliness may cause trouble.',
'संयमित खर्च, एकान्त शान्ति, विदेश परिश्रम, मोक्ष बल',
'अनिद्रा, एकान्त उदासी, विदेश कठिनाइ',
'विदेशी सेवा, अस्पताल, आश्रम, खनन',
'खर्च नियन्त्रण, विदेशबाट स्थिर आय',
'परिवारबाट टाढा, एकान्त जीवन',
'द्वादशस्थो शनिर्मोक्षं ददाति',
'Brihat Parashara Hora Shastra',
'शनिवार तिल तेल दान र शनि मन्त्र जप।'),

(8,2,
'राहु दोस्रो भावमा अचानक र अपरम्परागत धन दिन्छ। विदेशी र प्रविधिमा आधारित आय आउँछ। पैसाप्रति जुनून बढ्छ तर उतार-चढाव पनि त्यस्तै हुन्छ।',
'Rahu in the second gives sudden and unconventional wealth. Income rests on foreign and technology sources. Obsession with money grows but the fluctuations are equally strong.',
'अचानक धन, विदेशी आय, प्रविधि व्यापार, अपरम्परागत वाणी',
'धनमा अति जुनून, उतार-चढाव, मिथ्या वाणी',
'प्रविधि, आयात-निर्यात, फर्जी व्यापार, मनोरञ्जन',
'अचानक लाभ र अचानक हानि दुवै',
'परिवारमा अपरम्परागत व्यवहार',
'द्वितीयस्थो राहुरप्रत्यक्धनं ददाति',
'Saravali',
'राहु मन्त्र जप र नारियल विसर्जन।'),

(8,3,
'राहु तेस्रो भावमा असाधारण साहस र नवीन प्रविधिमा दक्षता दिन्छ। छोटो यात्रामा अचानक परिवर्तन हुन्छ। भाइबहिनीसँग अपरम्परागत सम्बन्ध रहन्छ।',
'Rahu in the third gives extraordinary courage and skill in new technology. Sudden changes occur in short journeys. An unconventional relationship remains with siblings.',
'असाधारण साहस, प्रविधि दक्षता, नवीन पहल, विदेशी सम्पर्क',
'अति जोखिम, भाइबहिनीसँग भ्रम, उतावली',
'प्रविधि, मिडिया, ह्याकिङ विज्ञान, विमान यात्रा',
'प्रविधि र यात्राबाट अचानक लाभ',
'भाइबहिनीसँग अपरम्परागत सम्बन्ध',
'तृतीयस्थो राहुर्वीर्यवान् भवति',
'Brihat Jataka',
'राहु मन्त्र जप र दुर्गा सप्तशती पाठ।'),

(8,4,
'राहु चौथो भावमा अपरम्परागत घर र विदेशी सम्पत्ति दिन्छ। मातासँग भावनात्मक उतार-चढाव रहन्छ। प्रविधिमा आधारित सुख र वाहन भोग बढ्छ।',
'Rahu in the fourth gives an unconventional home and foreign property. Emotional ups and downs remain with the mother. Comfort through technology based pleasures and vehicles grows.',
'विदेशी सम्पत्ति, प्रविधि सुख, अपरम्परागत घर, भूमि लाभ',
'मातासँग भ्रम, घर अस्थिरता, भूमि विवाद',
'प्रविधि भवन, आयात, वाहन व्यापार, विदेशी निर्माण',
'विदेशी जग्गा र प्रविधिबाट लाभ',
'परिवारमा अपरम्परागत ढाँचा',
'चतुर्थस्थो राहुर्गृहं कलयति',
'Saravali',
'राहु मन्त्र जप र छत्री दान।'),

(8,5,
'राहु पाँचौं भावमा अपरम्परागत बुद्धि र अचानक अटकलबाजी लाभ दिन्छ। नवीन प्रविधिमा शिक्षा र सन्तान विदेशमा हुन सक्छ। रहस्यमय विषयमा गहिरो रुचि रहन्छ।',
'Rahu in the fifth gives unconventional intellect and sudden gains in speculation. Education in new technology and children abroad are possible. Deep interest remains in mysterious subjects.',
'अचानक सट्टा लाभ, नवीन शिक्षा, रहस्य रुचि, प्रविधि बुद्धि',
'सट्टा जोखिम, सन्तान भ्रम, अनैतिक लाभ',
'प्रविधि शिक्षा, अनुसन्धान, फर्जी व्यापार, ज्योतिष',
'अचानक लाभ र अचानक हानि दुवै',
'सन्तानसँग भावनात्मक दूरी',
'पञ्चमस्थो राहुर्मेधावी भवति',
'Brihat Parashara Hora Shastra',
'राहु मन्त्र जप र गणेश पूजा।'),

(8,6,
'राहु छैटौं भावमा अपरम्परागत माध्यमले शत्रुलाई परास्त गर्छ। प्रविधि र विदेशी सेवामा प्रतिष्ठा मिल्छ। अचानक रोग र विवाद हुन सक्छ तर जीत रहन्छ।',
'Rahu in the sixth defeats enemies through unconventional means. Respect comes in technology and foreign service. Sudden illness and disputes may occur though victory remains.',
'अपरम्परागत विजय, प्रविधि सेवा, शत्रु पराजय, अचानक लाभ',
'अचानक रोग, कानुनी विवाद, विष जोखिम',
'प्रविधि, आयात-निर्यात, फर्जी व्यापार, अनुसन्धान',
'अनियमित तर बढी आय, ऋण फिर्ता',
'शत्रुसँग अचानक विजय',
'षष्ठस्थो राहुर्रिपुं हन्ति',
'Phaladeepika',
'राहु मन्त्र जप र नारियल दान।'),

(8,8,
'राहु आउठौं भावमा रहस्य र अचानक परिवर्तनको शक्तिशाली प्रभाव दिन्छ। विरासत र विदेशी स्रोतबाट अनपेक्षित लाभ हुन्छ। जीवनमा उतार-चढाव तीव्र हुन्छ तर गूढ ज्ञान प्राप्त हुन्छ।',
'Rahu in the eighth gives a powerful influence of mystery and sudden change. Unexpected gain comes through inheritance and foreign sources. Life fluctuations are intense though profound knowledge is gained.',
'अचानक परिवर्तन, विरासत लाभ, गूढ ज्ञान, विदेशी स्रोत',
'तीव्र उतार-चढाव, अचानक संकट, विष जोखिम',
'अनुसन्धान, प्रविधि, बीमा, विरासत कार्य',
'अचानक ठूलो लाभ र हानि दुवै',
'गोपनीयता, जीवनसाथीसँग उतार-चढाव',
'अष्टमस्थो राहुर्भयं ददाति',
'Saravali',
'राहु मन्त्र जप र दुर्गा सप्तशती पाठ।'),

(8,9,
'राहु नवौं भावमा अपरम्परागत धर्म र विदेशी गुरुलाई जोड्छ। भाग्य अचानक टर्छ तर धर्मप्रति शंका पनि हुन्छ। विदेश यात्रामा आध्यात्मिक अनुभव हुन सक्छ।',
'Rahu in the ninth links unorthodox dharma with foreign teachers. Fortune turns suddenly though doubt about dharma also arises. Spiritual experience may occur in foreign travel.',
'अचानक भाग्योदय, विदेशी गुरु, अपरम्परागत धर्म, विदेश यात्रा',
'धर्ममा शंका, पितासँग भ्रम, मिथ्या गुरु',
'विदेश शिक्षा, धर्म अनुसन्धान, पर्यटन, प्रविधि',
'विदेशी भाग्यबाट अचानक लाभ',
'पिता-गुरुसँग अपरम्परागत सम्बन्ध',
'नवमस्थो राहुर्भाग्यं करोति',
'Brihat Jataka',
'राहु मन्त्र जप र गुरु पूजा।'),

(8,11,
'राहु एघारौं भावमा अचानक र ठूलो लाभ दिन्छ। विदेशी सम्पर्क र प्रविधिबाट आय आउँछ। इच्छा अत्यन्त बलियो हुन्छ तर पूरा भएपछि पनि तृप्ति नहुने स्वभाव रहन्छ।',
'Rahu in the eleventh gives sudden and large gains. Income comes through foreign contacts and technology. Desires become extremely strong though satisfaction may not follow even after fulfilment.',
'ठूलो अचानक लाभ, विदेशी जाल, प्रविधि आय, इच्छा शक्ति',
'अति लोभ, तृप्तिको अभाव, अनैतिक लाभ, उतार-चढाव',
'प्रविधि, विदेश व्यापार, मनोरञ्जन, फर्जी योजना',
'अचानक ठूलो आय, तर अनिश्चित स्थिरता',
'विस्तृत तर अनिश्चित मित्र जाल',
'एकादशस्थो राहुर्लाभं ददाति',
'Phaladeepika',
'राहु मन्त्र जप र नारियल विसर्जन।'),

(8,12,
'राहु बाह्रौं भावमा विदेश वास र अचानक विदेशी खर्च ल्याउँछ। स्वप्न र रहस्यमा गहिरो रुचि रहन्छ। मोक्षमार्ग अपरम्परागत हुन्छ तर अन्ततः माया छाड्ने अनुभव हुन्छ।',
'Rahu in the twelfth brings foreign residence and sudden foreign expenditure. Deep interest remains in dreams and mysteries. The path of liberation is unconventional though the experience of letting go of illusion ultimately comes.',
'विदेश वास, स्वप्न ज्ञान, अपरम्परागत मोक्ष, अचानक परिवर्तन',
'अचानक विदेशी खर्च, अनिद्रा, भ्रम, गोप्य शत्रु',
'विदेशी सेवा, प्रविधि, अनुसन्धान, एकान्त कार्य',
'विदेशबाट अचानक लाभ र खर्च दुवै',
'परिवारबाट टाढा, गोपनीय सम्बन्ध',
'द्वादशस्थो राहुर्मोक्षं कल्पयति',
'Saravali',
'राहु मन्त्र जप र शनिवार तिल दान।'),

(9,2,
'केतु दोस्रो भावमा धनप्रति वैराग्य र आध्यात्मिक वाणी दिन्छ। भौतिक सम्पत्तिमा कम आसक्ति रहन्छ तर ज्ञानबाट आय आउँछ। परिवारमा आध्यात्मिक वातावरण रहन्छ।',
'Ketu in the second gives detachment from wealth and spiritual speech. Attachment to material property stays low though income comes through knowledge. A spiritual atmosphere persists in the family.',
'वैराग्य, आध्यात्मिक वाणी, ज्ञानबाट आय, सादगी',
'धन आसक्ति कम, वाणी मौनता, परिवार दूरी',
'अध्ययन, आध्यात्मिक कार्य, अनुसन्धान, उपचार',
'अनपेक्षित रूपमा धन आगमन-व्यय दुवै',
'परिवारसँग भावनात्मक दूरी',
'द्वितीयस्थो केतुर्वैराग्यवान् भवति',
'Phaladeepika',
'केतु मन्त्र जप र गणेश पूजा।'),

(9,3,
'केतु तेस्रो भावमा आध्यात्मिक साहस र अनुसन्धानमा दक्षता दिन्छ। लेखन र ज्ञानबाट प्रभाव रहन्छ। भाइबहिनीप्रति वैराग्य तर तीर्थ यात्रामा पुण्य मिल्छ।',
'Ketu in the third gives spiritual courage and skill in research. Influence remains through writing and knowledge. There is detachment from siblings though merit is gained on pilgrimage.',
'आध्यात्मिक साहस, अनुसन्धान दक्षता, लेखन ज्ञान, तीर्थ पुण्य',
'भाइबहिनी दूरी, मौनता, अधूरो सम्बन्ध',
'अनुसन्धान, लेखन, आध्यात्मिक शिक्षा, ज्योतिष',
'ज्ञानबाट अनियमित आय',
'भाइबहिनीसँग कम सम्पर्क तर आदर',
'तृतीयस्थो केतुर्ज्ञानवान् भवति',
'Brihat Jataka',
'केतु मन्त्र जप र गणेश पूजा।'),

(9,4,
'केतु चौथो भावमा भौतिक सुखप्रति वैराग्य र आन्तरिक शान्ति दिन्छ। घर सादा र आध्यात्मिक हुन्छ। माताप्रति गहिरो भक्ति रहन्छ तर भौतिक सुखमा कम रुचि हुन्छ।',
'Ketu in the fourth gives detachment from material comfort and inner peace. The home is simple and spiritual. Deep devotion to the mother remains though interest in physical pleasure is low.',
'आन्तरिक शान्ति, सादा घर, माताप्रति भक्ति, आध्यात्मिक सुख',
'भौतिक सुख कम, घर दूरी, उदासी',
'आध्यात्मिक कार्य, अनुसन्धान, शिक्षण, सेवा',
'सम्पत्तिमा कम आसक्ति, अनपेक्षित स्रोत',
'परिवारसँग कम भौतिक तर गहिरो भावना',
'चतुर्थस्थो केतुर्शान्तिं ददाति',
'Saravali',
'केतु मन्त्र जप र गणेश पूजा।'),

(9,5,
'केतु पाँचौं भावमा अध्यात्म बुद्धि र पूर्वजन्मको पुण्य दिन्छ। रहस्यमय विषयमा गहिरो अनुसन्धान हुन्छ। सन्तानप्रति वैराग्य तर विद्यामा ख्याति मिल्छ।',
'Ketu in the fifth gives spiritual intellect and merit of past lives. Deep research happens in mysterious subjects. Detachment from children though fame comes in learning.',
'अध्यात्म बुद्धि, पूर्व पुण्य, गहिरो अनुसन्धान, विद्या ख्याति',
'सन्तान दूरी, सट्टेबाजी हानि, एकान्त अध्ययन',
'अनुसन्धान, ज्योतिष, आध्यात्मिक शिक्षण, चिकित्सा',
'अटकलबाजीबाट हानि, ज्ञानबाट लाभ',
'सन्तानसँग भावनात्मक दूरी',
'पञ्चमस्थो केतुर्ज्ञानी भवति',
'Brihat Parashara Hora Shastra',
'केतु मन्त्र जप र गणेश विघ्ननाशक पूजा।'),

(9,6,
'केतु छैटौं भावमा आध्यात्मिक शक्तिले शत्रुलाई जित्छ। उपचार र सेवामा प्रतिष्ठा मिल्छ। अचानक छोटो रोग हुन सक्छ तर रोग प्रतिरोधात्मक शक्ति रहन्छ।',
'Ketu in the sixth wins enemies through spiritual power. Respect comes in healing and service. Sudden minor illness may occur though disease resistance remains.',
'आध्यात्मिक विजय, उपचार कौशल, सेवा प्रतिष्ठा, रोग प्रतिरोध',
'अचानक छोटो रोग, भय, शत्रु भ्रम',
'उपचार, आध्यात्मिक सेवा, अनुसन्धान, चिकित्सा',
'अनियमित आय, ऋण ढिलो फिर्ता',
'शत्रुसँग आध्यात्मिक दृष्टिले सुलह',
'षष्ठस्थो केतुर्रिपुं जयति',
'Phaladeepika',
'केतु मन्त्र जप र गणेश पूजा।'),

(9,8,
'केतु आउठौं भावमा गहिरो रहस्य ज्ञान र आध्यात्मिक परिवर्तन दिन्छ। विरासतमा अनिश्चितता रहन्छ तर अचानक आध्यात्मिक अनुभव हुन्छ। दीर्घ रोग र अनुसन्धान सँगै चल्छ।',
'Ketu in the eighth gives deep mysterious knowledge and spiritual transformation. Uncertainty remains in inheritance though sudden spiritual experience occurs. Long illness goes along with research.',
'गूढ ज्ञान, आध्यात्मिक परिवर्तन, अनुसन्धान शक्ति, दीर्घायु',
'विरासत अनिश्चितता, अचानक संकट, दीर्घ रोग',
'अनुसन्धान, ज्योतिष, उपचार, आध्यात्मिक अध्ययन',
'अनपेक्षित विरासत, तर भौतिक कम आसक्ति',
'गोपनीयता र आध्यात्मिक साधना',
'अष्टमस्थो केतुर्मोक्षं ददाति',
'Saravali',
'केतु मन्त्र जप र शिवलिङ्गमा जल।'),

(9,9,
'केतु नवौं भावमा उच्च धर्म र मोक्षमार्गको ज्ञान दिन्छ। भाग्यप्रति कम आसक्ति रहन्छ तर गुरु र आध्यात्मिक अनुभवबाट पूर्ण मार्गदर्शन मिल्छ।',
'Ketu in the ninth gives knowledge of high dharma and the path of liberation. Attachment to fortune stays low though complete guidance comes from the teacher and spiritual experience.',
'उच्च धर्म, मोक्ष ज्ञान, गुरु मार्गदर्शन, पूर्व पुण्य',
'भाग्य आसक्ति कम, धर्ममा शंका, पिता दूरी',
'आध्यात्मिक शिक्षण, अनुसन्धान, धर्म सेवा, ज्योतिष',
'भाग्यबाट अनियमित स्रोत, पुण्यबाट आय',
'गुरुप्रति गहिरो भक्ति, पितासँग कम सम्बन्ध',
'नवमस्थो केतुर्धर्मवान् भवति',
'Brihat Jataka',
'केतु मन्त्र जप र गुरु पूजा।'),

(9,11,
'केतु एघारौं भावमा इच्छाप्रति वैराग्य र आध्यात्मिक लाभ दिन्छ। भौतिक इच्छा कम रहन्छ तर अनपेक्षित स्रोतबाट आय आउँछ। मित्र चक्र आध्यात्मिक र कम हुन्छ।',
'Ketu in the eleventh gives detachment from desire and spiritual gain. Material desires stay low though income arrives through unexpected sources. The friend circle is spiritual and small.',
'वैराग्य लाभ, आध्यात्मिक मित्र, अनपेक्षित स्रोत, इच्छा शान्ति',
'इच्छा कमता, मित्र कम, भौतिक लाभ कम',
'आध्यात्मिक कार्य, अनुसन्धान, सेवा, शिक्षण',
'अनपेक्षित रूपमा आय, तर आसक्ति कम',
'कम तर गहिरो मित्रता',
'एकादशस्थो केतुर्लाभं ददाति',
'Phaladeepika',
'केतु मन्त्र जप र गणेश पूजा।'),

(9,12,
'केतु बाह्रौं भावमा मोक्ष र माया छाड्ने शक्ति दिन्छ। एकान्त र विदेशमा आध्यात्मिक अभ्यास फल्छ। भौतिक संसारप्रति कम आसक्तिले अन्ततः मुक्तिको मार्ग खुल्छ।',
'Ketu in the twelfth gives the power of liberation and letting go of illusion. Spiritual practice flourishes in isolation and abroad. Low attachment to the material world ultimately opens the path of freedom.',
'मोक्ष बल, माया छाड्ने अनुभव, एकान्त साधना, विदेश अभ्यास',
'एकान्त उदासी, भौतिक उपेक्षा, विवाद कम',
'आध्यात्मिक सेवा, अस्पताल, आश्रम, अनुसन्धान',
'खर्च कम तर भौतिक स्रोत पनि कम',
'परिवारबाट एकान्त, आध्यात्मिक स्वतन्त्रता',
'द्वादशस्थो केतुर्मोक्षं ददाति',
'Brihat Parashara Hora Shastra',
'केतु मन्त्र जप र गणेश पूजा।');
