-- Seed : graha_rashi  (12 rows) — own and key placements
-- Run after seed_combo_bhava_a.sql and seed_combo_bhava_b.sql

USE vedic_astrology_learn;

INSERT INTO graha_rashi (graha_id, rashi_id, interpretation_np, interpretation_en, positive_effects, challenges, career_indication, financial_indication, relationship_indication, classical_interpretation, sanskrit_reference, remedies) VALUES
(1,1,'सूर्य मेष राशिमा मित्र राशिमा रहँदा पराक्रमी र नेतृत्वमा सक्षम हुन्छ। आत्मविश्वास चरममा हुन्छ।','Sun in Aries, in a friendly sign, makes the native valorous and capable of leadership. Self-confidence is at its peak.','साहस, नेतृत्व, पराक्रम, सरकारी सम्मान','अहंकार, जल्दबाजी','राज्यसेवा, प्रशासन, सेना','सरकारी स्रोतबाट लाभ','आत्ममहत्वले द्वन्द्व','सूर्यो मेषे बलवान् भवति','Brihat Parashara Hora Shastra, Adhyaya 2','रविवार सूर्यलाई जल अर्पण।'),
(1,5,'सूर्य सिंह राशिमा स्वकीय राशिमा रहँदा सबैभन्दा बलियो हुन्छ। राज्य तुल्य सम्मान प्राप्त हुन्छ।','Sun in Leo, in its own sign, is at its strongest. Royal-equivalent honour is obtained.','शक्ति, प्रतिष्ठा, उच्च पद, दीर्घायु','अति अहंकार, दर्प','राज्य, प्रशासन, नेतृत्व','मजबूत आय, स्थिर सम्पत्ति','सम्मानित जीवनसाथी','सिंहे सूर्यः स्वगृहस्थो महत्कीर्तिः','Brihat Parashara Hora Shastra, Adhyaya 2','रविवार सूर्य मन्त्र जप।'),
(2,4,'चन्द्र कर्क राशिमा स्वकीय र उच्चमा रहँदा अत्यन्त शुभ हुन्छ। मन शान्त र मातृ स्नेह प्राप्त हुन्छ।','Moon in Cancer, in its own sign and exalted, is highly auspicious. The mind is peaceful and maternal love is obtained.','मानसिक शान्ति, मातृ स्नेह, लोकप्रियता, सम्पत्ति','भावनामा अति गहिराइ','जनसेवा, खाद्य, शिक्षा','जल र कृषिबाट लाभ','मातृ सुख, भावनात्मक सम्बन्ध','चन्द्रो कर्के स्वगृहे च शुभो भवति','Brihat Parashara Hora Shastra, Adhyaya 3','सोमबार शिवलिंगमा जल चढाउने।'),
(3,1,'मङ्गल मेष राशिमा स्वकीय राशिमा रहँदा पराक्रमी र शक्तिशाली बन्छ। साहस चरममा हुन्छ।','Mars in Aries, in its own sign, makes the native valorous and powerful. Courage is at its peak.','अत्यधिक साहस, शारीरिक बल, विजय','क्रोध, दुर्घटना, विवाद','सेना, खेलकुद, इन्जिनियरिङ','भूमि र पराक्रमबाट लाभ','तीव्र भावना, विवाद','मङ्गलो मेषे स्वगृहे वीर्यवान्','Brihat Parashara Hora Shastra, Adhyaya 6','मङ्गलबार हनुमान चालीसा।'),
(3,8,'मङ्गल वृश्चिक राशिमा स्वकीय राशिमा रहँदा गहिरो अनुसन्धान शक्ति र तीव्र परिवर्तन दिन्छ।','Mars in Scorpio, in its own sign, gives deep research power and intense transformation.','अनुसन्धान क्षमता, परिवर्तन, संकटमा टिकाउपन','तीव्रता, रहस्यवाद','अनुसन्धान, चिकित्सा, सुरक्षा','अचानक लाभ, तर उतारचढाव','तीव्र भावना, गहिरो सम्बन्ध','मङ्गलो वृश्चिके स्वगृहे परिवर्तनप्रियो','Brihat Parashara Hora Shastra, Adhyaya 6','मङ्गलबार रुद्राभिषेक गर्ने।'),
(4,3,'बुध मिथुन राशिमा स्वकीय राशिमा रहँदा बुद्धिमान र वाणीपटु हुन्छ। तर्क र सञ्चारमा उत्कृष्टता हुन्छ।','Mercury in Gemini, in its own sign, makes the native intelligent and eloquent. There is excellence in reasoning and communication.','बुद्धिमत्ता, वाणी कला, बहुभाषिक दक्षता','द्विधा, अति बोली','लेखन, सञ्चार, व्यापार','व्यापारबाट लाभ','संवादमा दक्ष, तर भावना कम','बुधो मिथुने स्वगृहे वाक्पटु','Brihat Parashara Hora Shastra, Adhyaya 10','बुधवार गणेशलाई दूर्वा चढाउने।'),
(5,9,'गुरु धनु राशिमा स्वकीय राशिमा रहँदा ज्ञानी र भाग्यवान हुन्छ। धर्म र उच्च शिक्षामा उन्नति हुन्छ।','Jupiter in Sagittarius, in its own sign, makes the native learned and fortunate. There is progress in dharma and higher education.','ज्ञान, भाग्य, धर्म, दीर्घायु','अति उदारता','शिक्षण, धर्म, विधि','भाग्यबाट लाभ','ज्ञानी जीवनसाथी','गुरुर्धनौ स्वगृहे धर्मप्रियो','Brihat Parashara Hora Shastra, Adhyaya 11','गुरुवार विष्णु मन्त्र जप।'),
(5,12,'गुरु मीन राशिमा उच्चमा रहँदा अत्यन्त शुभ मानिन्छ। ज्ञान, भाग्य र आध्यात्मिक उन्नति हुन्छ।','Jupiter in Pisces, exalted, is considered highly auspicious. There is growth in knowledge, fortune and spirituality.','अत्यधिक ज्ञान, भाग्य, आध्यात्मिक सिद्धि','अति आशावाद','शिक्षण, आध्यात्मिक कार्य, विदेश','भाग्यबाट ठूलो लाभ','भाग्यवान जीवनसाथी','गुरुर्मीने उच्चस्थः शुभो भवति','Brihat Parashara Hora Shastra, Adhyaya 11','गुरुवार गायलाई चना खुवाउने।'),
(6,7,'शुक्र तुला राशिमा स्वकीय राशिमा रहँदा वैवाहिक सुख र कलात्मक उन्नति दिन्छ।','Venus in Libra, in its own sign, gives marital happiness and artistic progress.','वैवाहिक सुख, कलात्मक दक्षता, सौन्दर्य','सान्द्रता','कला, डिजाइन, मनोरञ्जन','भौतिक सुख र धन','उत्तम जीवनसाथी','शुक्रस्तुले स्वगृहे शुभो भवति','Brihat Parashara Hora Shastra, Adhyaya 13','शुक्रबार लक्ष्मी मन्त्र जप।'),
(7,10,'शनि मकर राशिमा स्वकीय राशिमा रहँदा कर्म क्षेत्रमा उच्च पद दिन्छ। श्रमको पूर्ण फल मिल्छ।','Saturn in Capricorn, in its own sign, gives high position in career. The fruit of labour is fully obtained.','अनुशासन, उच्च पद, दिगो स्थिरता, धैर्य','कठोरता, उदासीनता','प्रशासन, खनन, यन्त्र उद्योग','स्थिर र दिगो आय','जिम्मेवार तर भावना कम','शनिर्मकरे स्वगृहे कर्मप्रियो','Brihat Parashara Hora Shastra, Adhyaya 15','शनिवार शनि मन्त्र जप।'),
(7,11,'शनि कुम्भ राशिमा स्वकीय राशिमा रहँदा वैज्ञानिक बुद्धि र सामाजिक सेवामा सफलता दिन्छ।','Saturn in Aquarius, in its own sign, gives scientific thinking and success in social service.','वैज्ञानिक बुद्धि, मित्र वृद्धि, लाभ वृद्धि','भावनात्मक दूरी','विज्ञान, प्रविधि, सामाजिक कार्य','स्थिर आय, बचत','मित्र समूहमा सक्रिय','शनिः कुम्भे स्वगृहे मित्रप्रियो','Brihat Parashara Hora Shastra, Adhyaya 15','शनिवार तिल तेल दान।'),
(8,2,'राहु वृषभ राशिमा बलियो अवस्थामा रहँदा भौतिक सुख र विलासितामा उन्नति दिन्छ। स्थिरताको भाव देखिन्छ।','Rahu in Taurus, in a strong position, gives progress in material comfort and luxury. There is a sense of stability.','भौतिक समृद्धि, स्थिर लाभ, विलासिता','अति भौतिकता, मोह','कला, अभिनय, प्रविधि','ठूलो र स्थिर लाभ','मोह र स्नेहको अस्थिरता','राहुर्वृषभे भौतिकसुखं ददाति','Brihat Parashara Hora Shastra, Adhyaya 17','दुर्गा सप्तशतीको पाठ गर्ने।');
