-- =====================================================================
-- संयोजन विश्लेषण — complete Graha + Bhava Faladesh (part A)
-- Adds bhavas 2,3,4,5,6,8,9,11,12 for grahas 1-3 (Surya, Chandra, Mangala).
-- Existing rows for bhavas 1,7,10 are kept (INSERT IGNORE is idempotent).
-- Content: structured knowledge data, written in own words.
-- =====================================================================

USE vedic_astrology_learn;

INSERT IGNORE INTO `graha_bhava` (`graha_id`,`bhava_id`,`interpretation_np`,`interpretation_en`,`positive_effects`,`challenges`,`career_indication`,`financial_indication`,`relationship_indication`,`classical_interpretation`,`sanskrit_reference`,`remedies`) VALUES

(1,2,
'सूर्य दोस्रो भावमा धन संचयकर्ता हुन्छ। आफ्नो परिश्रम र सरकारी स्रोतबाट आय आउँछ। वाणीमा आधिकारिक भाव रहन्छ तर परिवारभित्र अहम् देखिन सक्छ।',
'Sun in the second accumulates wealth. Income comes through own effort and government sources. Speech carries authority though ego may show within the family.',
'धन संचय, वाणीमा आधिकारिकता, परिवारमा नेतृत्व, उच्च आदर्श',
'अहंकार, परिवारसँग मतभेद, स्वास्थ्यमा ताप',
'बैंक, राजकोष, प्रशासन, उद्यम',
'दीर्घकालीन बचत र सम्पत्ति वृद्धि',
'परिवारमा आफ्नो कुरा मान्ने जिद',
'सूर्यो द्वितीयस्थो धनवान् भवति',
'Brihat Parashara Hora Shastra',
'रविवार सूर्यलाई जल अर्पण गर्ने।'),

(1,3,
'सूर्य तेस्रो भावमा पराक्रमी र साहसी बनाउँछ। आत्मबलमा विश्वास गरेर सबै काम आफैं गर्ने प्रवृत्ति हुन्छ। छोटो यात्रा र आत्म-प्रयासबाट सफलता मिल्छ, तर भाइबहिनीसँग अहम् टकराव हुन सक्छ।',
'Sun in the third makes the person courageous and valiant. There is a tendency to do everything by self effort. Success comes through short journeys and initiative, though ego clashes with siblings may occur.',
'साहस, आत्मनिर्भरता, पहलकदमी, भाइबहिनीमा नेतृत्व',
'अहम् टकराव, जल्दबाजी, छोटो यात्रामा अवरोध',
'पत्रकारिता, विपणन, सेना, सूचना प्रविधि',
'आत्मप्रयासबाट स्थिर आय, तर खर्च पनि बढी',
'भाइबहिनीसँग प्रतिस्पर्धा, तर आदर पनि',
'तृतीयस्थः सूर्यो वीर्यवान् भवति',
'Phaladeepika',
'रविवार सूर्य मन्त्र जप र कर्पूर दीप दान।'),

(1,4,
'सूर्य चौथो भावमा घर-परिवारमा असन्तोष र मातासँग भावनात्मक दूरी दिन्छ। भूमि र सम्पत्तिमा ढिलाइपछि सफलता मिल्छ। गाउँ-समाजमा सम्मान तर घरभित्र तनाव रहन सक्छ।',
'Sun in the fourth brings dissatisfaction at home and emotional distance from the mother. Success in land and property comes after delay. There is respect in the community though tension may persist within the house.',
'भूमि र सम्पत्ति, समाजमा सम्मान, घर स्थापना, पछि उन्नति',
'मातासँग मतभेद, घरमा तनाव, भूमिमा विवाद',
'भवन निर्माण, भूमि व्यवसाय, प्रशासन, शिक्षा',
'जग्गा र घरबाट लाभ, तर लगानी ढिलो',
'पारिवारिक भावनात्मक दूरी',
'चतुर्थस्थः सूर्यो गृहसुखप्रदो भवति',
'Brihat Jataka',
'सूर्यलाई जल अर्पण र घरमा दीप बाल्ने।'),

(1,5,
'सूर्य पाँचौं भावमा बुद्धि र विद्यामा प्रबलता दिन्छ। सन्तानप्रति अपेक्षा बढी रहन्छ र सन्तानले कठिनाइ दिन सक्छ। धार्मिक विचार, शिक्षा र पुण्यबाट सम्मान मिल्छ।',
'Sun in the fifth strengthens intellect and learning. Expectations from children remain high and children can cause difficulty. Respect comes through religious outlook, education and merit.',
'तीव्र बुद्धि, विद्यामा उत्कृष्टता, धार्मिक प्रवृत्ति, पुण्य बल',
'सन्तानसँग मतभेद, प्रेममा अहम्, सट्टेबाजीमा हानि',
'शिक्षण, अनुसन्धान, धार्मिक कार्य, शेयर बजार',
'अटकलबाजीबाट लाभ-हानि दुवै, पुरानो सम्पत्तिबाट आय',
'प्रेममा अहम्, सन्तानसँग गम्भीर सम्बन्ध',
'पञ्चमस्थः सूर्यो धर्मप्रियो भवति',
'Saravali',
'सूर्य मन्त्र जप र विद्यार्थीलाई दान गर्ने।'),

(1,6,
'सूर्य छैटौं भावमा शत्रुलाई परास्त गर्ने शक्ति दिन्छ। रोग प्रतिरोधात्मक क्षमता बलियो हुन्छ। सेवा र प्रशासनमा प्रतिष्ठा पाउँछ, तर कहिलेकाहीँ क्रोध र अहंकारले विवाद बढाउँछ।',
'Sun in the sixth grants the power to defeat enemies. Resistance to disease stays strong. Respect comes through service and administration, though anger and ego may sometimes increase disputes.',
'शत्रु पराजय, रोग प्रतिरोध, सेवामा प्रतिष्ठा, प्रशासनिक क्षमता',
'क्रोध, विवाद, पेट र आँखा समस्या',
'प्रशासन, चिकित्सा, वकालत, सुरक्षा',
'ऋण फिर्ता, नियमित आय, तर विवादमा खर्च',
'सहकर्मीसँग तनाव, सेवाभावी मित्र',
'सूर्यो षष्ठस्थो रिपुं जयति',
'Phaladeepika',
'रविवार तिल-तेल दान र सूर्य मन्त्र जप।'),

(1,8,
'सूर्य आउठौं भावमा जीवनमा उतार-चढाव र अचानक परिवर्तन ल्याउँछ। आयु र स्वास्थ्यमा सावधानी चाहिन्छ। रहस्य र अनुसन्धानमा रुचि बढ्छ, छानबिन र विरासतबाट लाभ हुन सक्छ।',
'Sun in the eighth brings ups and downs and sudden changes in life. Care is needed for health and longevity. Interest grows in research and mysteries; gain may come through investigation and inheritance.',
'अनुसन्धान क्षमता, रहस्य ज्ञान, आकस्मिक उन्नति, दीर्घायु पछिको बल',
'अचानक परिवर्तन, स्वास्थ्य जोखिम, सत्ता संघर्ष',
'अनुसन्धान, कर र लेखा, चिकित्सा, गुप्तचरी',
'अनपेक्षित लाभ-हानि, विरासत र बीमाबाट आय',
'गोपनीयता र भावनात्मक दूरी',
'अष्टमस्थः सूर्यो आयुर्दायी भवति',
'Brihat Parashara Hora Shastra',
'सूर्यलाई जल अर्पण र गंगाजल दान गर्ने।'),

(1,9,
'सूर्य नवौं भावमा धर्म र भाग्यलाई बलियो बनाउँछ। पिता र गुरुको स्नेह मिल्छ। उच्च शिक्षा, तीर्थ र आध्यात्मिक कार्यबाट मान-सम्मान बढ्छ।',
'Sun in the ninth strengthens dharma and fortune. Affection of father and teacher is gained. Respect grows through higher education, pilgrimage and spiritual works.',
'भाग्य बल, धर्म प्रवृत्ति, पिताको स्नेह, उच्च शिक्षा',
'पितासँग दूरी, धर्ममा औपचारिकता, ढिलो भाग्योदय',
'शिक्षा, धर्म प्रचार, न्याय, सरकारी सेवा',
'भाग्यले अप्रत्याशित स्रोत, दानबाट वृद्धि',
'गुरु र पितासँग गहिरो सम्बन्ध',
'नवमस्थः सूर्यो भाग्यवान् भवति',
'Brihat Jataka',
'सूर्यलाई अर्घ्य दिई गुरु वन्दना गर्ने।'),

(1,11,
'सूर्य एघारौं भावमा आय र लाभको कारक हुन्छ। उच्च पदका व्यक्ति र पुराना सम्बन्धबाट सहयोग मिल्छ। आकांक्षा पूरा हुन्छ तर लोभमा परे लाभ घट्न सक्छ।',
'Sun in the eleventh is a significator of income and gain. Support comes from people of high position and old contacts. Ambitions are fulfilled though greed can reduce the gains.',
'आय वृद्धि, इच्छा पूर्ति, प्रभावशाली मित्र, उच्च पदको सहयोग',
'लोभ, मित्रसँग अहम्, अति आशावाद',
'व्यापार, प्रबन्धन, राजनीति, नेटवर्किङ',
'नियमित लाभ र बोनस, निवेशबाट आम्दानी',
'विस्तृत मित्रचक्र, परिवारसँग लाभ साझेदारी',
'एकादशस्थः सूर्यो लाभकृत् भवति',
'Phaladeepika',
'रविवार सूर्य मन्त्र जप र ज्येष्ठलाई सम्मान गर्ने।'),

(1,12,
'सूर्य बाह्रौं भावमा खर्च र विदेशसँग जोडिन्छ। सरकारी र विदेशी स्रोतबाट खर्च हुन्छ तर अन्ततः मुक्तिको मार्ग देखाउँछ। नेत्र र निद्रामा सावधानी राख्नुपर्छ।',
'Sun in the twelfth connects with expenditure and foreign lands. Expenses arise through government and foreign sources though the house ultimately shows the path of liberation. Care is needed for eyes and sleep.',
'विदेश वास, आध्यात्मिक उन्नति, मोक्ष मार्ग, गोपनीय स्रोतबाट लाभ',
'अनावश्यक खर्च, निद्रा समस्या, नेत्र पीडा',
'विदेशी संस्था, अस्पताल, आश्रम, विश्राम केन्द्र',
'खर्च बढी, बचत ढिलो, विदेशबाट आय',
'परिवारबाट टाढा रहने अवस्था',
'द्वादशस्थः सूर्यो मोक्षमार्गं दर्शयति',
'Saravali',
'सूर्यलाई जल अर्पण र नियमित ध्यान गर्ने।'),

(2,2,
'चन्द्र दोस्रो भावमा धन र परिवारमा स्नेह दिन्छ। माता र जनसम्पर्कबाट आय आउँछ। मिठो वाणी हुन्छ तर भावनाप्रधान खर्चले बचत उतार-चढाव गराउँछ।',
'Moon in the second brings affection for wealth and family. Income comes through the mother and public contact. Speech is sweet though emotional spending makes savings fluctuate.',
'मिठो वाणी, परिवार प्रेम, जनसम्पर्कबाट आय, कलात्मकता',
'भावनाप्रधान खर्च, उतार-चढाव, मानसिक चिन्ता',
'जनसम्पर्क, परामर्श, दृश्य कला, जल सम्बन्धी व्यवसाय',
'उतार-चढाव भए पनि परिवारबाट लाभ',
'परिवारसँग गहिरो भावनात्मक जडान',
'चन्द्रो द्वितीयस्थो धनवान् भवति',
'Brihat Parashara Hora Shastra',
'सोमवार चन्द्रलाई जल अर्पण गर्ने।'),

(2,3,
'चन्द्र तेस्रो भावमा कल्पनाशील र साहसी बनाउँछ। छोटो यात्रामा भावनात्मक सुख मिल्छ। भाइबहिनीप्रति स्नेह रहन्छ तर कहिलेकाहीँ मनमैयाबाट काम अधुरो हुन्छ।',
'Moon in the third makes one imaginative and courageous. Emotional happiness comes through short journeys. There is affection for siblings though work may sometimes be left incomplete out of moodiness.',
'कल्पनाशक्ति, साहस, भाइबहिनी स्नेह, यात्रा सुख',
'मनमैया, अधुरो काम, भावनात्मक अस्थिरता',
'सिनेमा, लेखन, विपणन, पर्यटन',
'लघु यात्राबाट लाभ, तर अनियमित आय',
'भाइबहिनी र छिमेकीसँग स्नेहपूर्ण सम्बन्ध',
'तृतीयस्थो चन्द्रो बुद्धिमान् भवति',
'Phaladeepika',
'सोमवार चन्द्र मन्त्र जप र जलार्पण गर्ने।'),

(2,4,
'चन्द्र चौथो भावमा आनन्द र शान्तिको कारक हुन्छ। माताको स्नेह र सुन्दर घर-वाहन सुख मिल्छ। भावनात्मक रूपमा शान्त रहन्छ तर कहिलेकाहीँ चिन्ताले मन डोलाउँछ।',
'Moon in the fourth is a giver of joy and peace. The affection of the mother and comfort of home and vehicles are gained. The mind is peaceful though anxiety can sometimes disturb it.',
'घर सुख, माताको स्नेह, वाहन सुख, भावनात्मक शान्ति',
'चिन्ता, घरमा उतार-चढाव, मन डोलने प्रवृत्ति',
'भवन सजावट, परामर्श, कृषि, जल सम्बन्ध',
'घर-जग्गाबाट लाभ, बचत भावनाप्रधान',
'माता र परिवारसँग गहिरो माया',
'चतुर्थस्थो चन्द्रो सुखदो भवति',
'Brihat Jataka',
'सोमवार चन्द्रलाई जल अर्पण र श्वेत वस्त्र दान।'),

(2,5,
'चन्द्र पाँचौं भावमा सिर्जनात्मक बुद्धि र सन्तानप्रति माया दिन्छ। कला र शिक्षामा रुचि रहन्छ। सट्टेबाजीबाट उतार-चढाव हुन्छ, तर विद्या र पुण्यबाट सुख मिल्छ।',
'Moon in the fifth gives creative intellect and love for children. Interest remains in arts and education. Speculation fluctuates, but happiness comes through learning and merit.',
'सिर्जनात्मक बुद्धि, सन्तान सुख, कला रुचि, विद्या प्रेम',
'सट्टेबाजीमा हानि, भावनात्मक निर्णय, सन्तानको चिन्ता',
'शिक्षा, कला, रचनात्मक उद्योग, मनोविज्ञान',
'अटकलबाजीबाट उतार-चढाव, पुरानो धनबाट सहयोग',
'सन्तान र शिष्यसँग मायापूर्ण सम्बन्ध',
'पञ्चमस्थो चन्द्रो मेधावी भवति',
'Saravali',
'सोमवार चन्द्र मन्त्र जप र कन्यालाई दही दान।'),

(2,6,
'चन्द्र छैटौं भावमा सेवा र परिश्रमबाट शत्रुलाई परास्त गर्ने शक्ति दिन्छ। चिन्ता र थकानले स्वास्थ्यमा उतार-चढाव आउँछ। सहकर्मी र रोगीसँग सेवाभावले सम्मान मिल्छ।',
'Moon in the sixth gives the power to overcome enemies through service and labour. Anxiety and fatigue cause health fluctuations. Respect is earned through care for colleagues and patients.',
'शत्रु पराजय, सेवा भाव, सहकर्मी सहयोग, रोग निवारण',
'चिन्ता, थकान, पेट र मानसिक तनाव',
'अस्पताल, सेवा, प्रशासन, खाद्य उद्योग',
'सेवाबाट आय, ऋण ढिलो तर फिर्ता',
'सहकर्मीसँग मधुर सम्बन्ध, शत्रुसँग सुलह',
'षष्ठस्थो चन्द्रो रिपुनाशकृत्',
'Phaladeepika',
'सोमवार जलार्पण र शिवलिङ्गमा जल चढाउने।'),

(2,8,
'चन्द्र आउठौं भावमा भावनात्मक उतार-चढाव र रहस्यमय अनुभव दिन्छ। विरासत र अनुसन्धानबाट लाभ हुन सक्छ। जीवनदैर्घ्य रहन्छ तर मानसिक शान्ति र जलजन्य रोगमा सावधानी चाहिन्छ।',
'Moon in the eighth brings emotional ups and downs and mysterious experiences. Gain may come through inheritance and research. Longevity remains though mental peace and watery ailments need care.',
'दीर्घायु, अनुसन्धान क्षमता, विरासत लाभ, गहन अन्तर्दृष्टि',
'भावनात्मक अस्थिरता, जलजन्य रोग, गोपनीय तनाव',
'अनुसन्धान, बीमा, ज्योतिष, कर कार्य',
'विरासत र अनपेक्षित स्रोत, तर उतार-चढाव',
'भावनात्मक गोपनीयता, जीवनसाथीसँग गहिराइ',
'अष्टमस्थो चन्द्रो आयुर्दायी',
'Brihat Parashara Hora Shastra',
'सोमवार चन्द्र मन्त्र जप र जलार्पण गर्ने।'),

(2,9,
'चन्द्र नवौं भावमा भक्ति र भाग्यलाई जोड्छ। माता र गुरुको आशीर्वादले उन्नति हुन्छ। तीर्थ र धार्मिक यात्रामा मन लाग्छ, तर मन डोलेसाथ भाग्य पनि डोल्छ।',
'Moon in the ninth links devotion with fortune. Progress comes through the blessings of mother and teacher. The mind is drawn to pilgrimage and religious travel, though fortune wavers as the mind wavers.',
'भक्ति भाव, भाग्य बल, माता-गुरु आशीर्वाद, तीर्थ सुख',
'मन डोल्ने प्रवृत्ति, भाग्यमा उतार-चढाव, अति भावुकता',
'धर्म प्रचार, शिक्षा, पर्यटन, कला',
'भाग्यले अप्रत्याशित लाभ, दानबाट वृद्धि',
'माता र गुरुप्रति कृतज्ञता, परिवारमा स्नेह',
'नवमस्थो चन्द्रो भाग्यवान् भवति',
'Brihat Jataka',
'सोमवार जलार्पण र शिव मन्त्र जप गर्ने।'),

(2,11,
'चन्द्र एघारौं भावमा लाभ र मित्रताको कारक हुन्छ। विस्तृत मित्रचक्र र सामाजिक सम्बन्धबाट आय आउँछ। इच्छा पूरा हुन्छ तर भावनाप्रधान निर्णयले कहिलेकाहीँ हानि पनि दिन्छ।',
'Moon in the eleventh signifies gains and friendship. Income arrives through a wide circle of friends and social contacts. Desires are fulfilled though emotional decisions can sometimes cause loss.',
'मित्रता, आय वृद्धि, सामाजिक लोकप्रियता, इच्छा पूर्ति',
'भावनाप्रधान लगानी, अति आशा, मित्रमा निर्भरता',
'सामाजिक कार्य, परामर्श, जनसम्पर्क, कला',
'नियमित लाभ र साझेदारीबाट आय',
'ठूलो मित्रचक्र, परिवारसँग लाभ साझा',
'एकादशस्थो चन्द्रो लाभकृत्',
'Phaladeepika',
'सोमवार चन्द्र मन्त्र जप र जलदान गर्ने।'),

(2,12,
'चन्द्र बाह्रौं भावमा विलासिता र विदेशसँग जोड्छ। सुख-सुविधामा खर्च र चिन्ता बढ्छ। विदेश वास र एकान्त अभ्यासबाट मानसिक शान्ति र मोक्षमार्ग प्रबल हुन्छ।',
'Moon in the twelfth connects with luxury and foreign places. Spending increases on comforts while worry grows. Foreign stay and quiet practice bring mental peace and strengthen the path of liberation.',
'विदेश सुख, एकान्त शान्ति, कल्पना शक्ति, मोक्ष मार्ग',
'अनावश्यक खर्च, अनिद्रा, चिन्ता र भ्रम',
'विदेशी संस्था, कला, अस्पताल, आश्रम',
'खर्च बढी, बचत कम, विदेशबाट आय',
'परिवारबाट टाढा, भावनात्मक एकान्तता',
'द्वादशस्थो चन्द्रो मोक्षप्रियो भवति',
'Saravali',
'सोमवार जलार्पण र शान्ति मन्त्र जप गर्ने।'),

(3,2,
'मंगल दोस्रो भावमा परिश्रमबाट धन दिन्छ। कडा वाणीले परिवारमा विवाद बढाउन सक्छ। जमिन र साहसिक कार्यबाट आय आउँछ, तर क्रोध नियन्त्रण गर्नुपर्छ।',
'Mars in the second gives wealth through hard labour. Harsh speech can increase disputes in the family. Income comes from land and ventures of courage, but anger needs to be controlled.',
'परिश्रमबाट धन, दृढ संकल्प, भूमि लाभ, निडर वाणी',
'कडा वाणी, पारिवारिक विवाद, क्रोध',
'इन्जिनियरिङ, खनन, सुरक्षा, खेलकुद',
'परिश्रमले आय, तर विवादले हानि पनि',
'परिवारसँग मौखिक टकराव',
'द्वितीयस्थो मङ्गलो धनवान् भवति',
'Brihat Parashara Hora Shastra',
'मंगलवार हनुमान मन्त्र जप र तिल तेल दान।'),

(3,3,
'मंगल तेस्रो भावमा असाधारण साहस र पहलकदमी दिन्छ। भाइबहिनी र साहसिक कार्यमा अग्रणी हुन्छ। छोटो यात्रामा ऊर्जा रहन्छ तर उतावलीमा चोटपटक हुन सक्छ।',
'Mars in the third grants extraordinary courage and initiative. The person leads among siblings and in ventures of valour. Energy stays high in short journeys though haste can bring minor injuries.',
'साहस, पहलकदमी, भाइबहिनीमा बल, यान्त्रिक कौशल',
'उतावली, चोटपटक, क्रोध',
'सेना, पुलिस, इन्जिनियरिङ, खेलकुद',
'साहसिक कार्यबाट लाभ, तर जल्दबाजीमा हानि',
'भाइबहिनीसँग प्रतिस्पर्धा तर रक्षा पनि',
'तृतीयस्थो मङ्गलो वीरो भवति',
'Phaladeepika',
'मंगलवार हनुमान मन्त्र जप र मसूर दान।'),

(3,4,
'मंगल चौथो भावमा घर र भूमिमा उत्तेजना ल्याउँछ। वाहन र मेसिनरीमा रुचि रहन्छ तर गृहस्थीमा अशान्ति हुन सक्छ। माताको स्वास्थ्यमा ध्यान दिनुपर्छ।',
'Mars in the fourth brings restlessness in home and land matters. Interest remains in vehicles and machinery though unease may persist in domestic life. Attention is needed to the health of the mother.',
'भूमि र वाहन सम्बन्धी लाभ, ऊर्जा, गृह निर्माण साहस',
'गृह कलह, जग्गा विवाद, माताको स्वास्थ्य',
'वाहन उद्योग, इन्जिनियरिङ, जमिन व्यवसाय',
'वाहन र भूमिबाट लाभ, तर विवादमा खर्च',
'घरमा तनाव, तर घरप्रति समर्पण',
'चतुर्थस्थो मङ्गलो गृहकलहप्रदः',
'Brihat Jataka',
'मंगलवार हनुमान मन्त्र जप र लाल मसूर दान।'),

(3,5,
'मंगल पाँचौं भावमा तीव्र बुद्धि दिन्छ तर धैर्य कम हुन्छ। सन्तानप्रति सख्त अनुशासन रहन्छ। सट्टेबाजीमा साहसिक निर्णयले ठूलो लाभ वा हानि दुवै हुन सक्छ।',
'Mars in the fifth gives a sharp intellect though patience is low. There is strict discipline towards children. Bold moves in speculation can bring either big gain or big loss.',
'तीव्र बुद्धि, साहसिक निर्णय, अनुशासन, प्रविधि ज्ञान',
'धैर्य कमता, सन्तानसँग द्वन्द्व, सट्टेबाजी जोखिम',
'प्रविधि, खेलकुद, अनुसन्धान, शिक्षण',
'साहसिक लगानीबाट उतार-चढाव',
'सन्तानसँग गम्भीर तर प्रेमपूर्ण अनुशासन',
'पञ्चमस्थो मङ्गलो धर्मज्ञो भवति',
'Saravali',
'हनुमान मन्त्र जप र मंगलवार व्रत राख्ने।'),

(3,6,
'मंगल छैटौं भावमा शत्रु र प्रतिस्पर्धामा विजय दिन्छ। सेवा र लडाइँमा अग्रणी हुन्छ। रक्त र बुखार जस्ता रोगमा सावधानी चाहिन्छ, तर ऋण फिर्ता हुन्छ।',
'Mars in the sixth grants victory over enemies and competition. The person is a leader in service and struggle. Care is needed for blood and febrile ailments though debts are repaid.',
'शत्रु विजय, प्रतिस्पर्धामा अग्रणी, ऋण मुक्ति, सेवा बल',
'बुखार, रक्त विकार, क्रोधजन्य विवाद',
'सुरक्षा, वकालत, शल्य चिकित्सा, खेलकुद',
'ऋण फिर्ता, प्रतिस्पर्धाबाट लाभ',
'शत्रुसँग कठोर तर विजयी मोलभाव',
'षष्ठस्थो मङ्गलो रिपुं हन्ति',
'Phaladeepika',
'मंगलवार हनुमान चालीसा र तेल दान गर्ने।'),

(3,8,
'मंगल आउठौं भावमा अचानक घटना र चोटपटकको सम्भावना राख्छ। शल्यक्रिया र अनुसन्धानमा सफलता मिल्छ। विरासतमा विवाद हुन सक्छ, तर दृढता र अन्तर्दृष्टि बढ्छ।',
'Mars in the eighth indicates sudden events and injury. Success comes in surgery and research. Disputes may arise over inheritance, but endurance and insight increase.',
'शल्य कौशल, अनुसन्धान शक्ति, आकस्मिक बल, विरासत लाभ',
'दुर्घटना, चोट, विरासत विवाद, क्रोध',
'शल्य चिकित्सा, अनुसन्धान, सुरक्षा, भूगर्भ',
'अचानक लाभ-हानि, विरासत विवाद',
'भावनात्मक तीव्रता र विवाद',
'अष्टमस्थो मङ्गलो रोगकृत् भवति',
'Brihat Parashara Hora Shastra',
'मंगलवार हनुमान मन्त्र जप र मसूर दान।'),

(3,9,
'मंगल नवौं भावमा धर्मप्रति साहस र अडिग विश्वास दिन्छ। पिता वा गुरुसँग मतभेद हुन सक्छ। तीर्थ यात्रा साहसिक हुन्छ, उच्च शिक्षामा संघर्षपछि सफलता मिल्छ।',
'Mars in the ninth gives courage of conviction in dharma. Differences with father or teacher may occur. Pilgrimage is adventurous and higher education brings success after struggle.',
'धर्म साहस, तीर्थ यात्रा, उच्च शिक्षामा विजय, अडिग विश्वास',
'पिता-गुरुसँग मतभेद, अति आक्रामकता, ढिलो भाग्योदय',
'धर्म प्रचार, सेना, वकालत, उच्च शिक्षा',
'दूरस्थ स्रोतबाट लाभ, तीर्थमा खर्च',
'पितासँग दूरी, गुरुप्रति सम्मान',
'नवमस्थो मङ्गलो धर्मवीर्यो भवति',
'Brihat Jataka',
'मंगलवार हनुमान मन्त्र जप र लाल दान।'),

(3,11,
'मंगल एघारौं भावमा प्रतिस्पर्धाबाट ठूलो लाभ दिन्छ। साहसिक योजनाबाट आय बढ्छ। सक्रिय र प्रभावशाली मित्रहरू हुन्छन् तर अति उत्साहले जोखिम पनि ल्याउँछ।',
'Mars in the eleventh brings large gains through competition. Income grows from bold plans. Friends are active and influential though excess enthusiasm can also carry risk.',
'प्रतिस्पर्धाबाट लाभ, सक्रिय मित्र, महत्वाकांक्षी योजना, ऊर्जा',
'अति जोखिम, आक्रामक व्यवहार, जल्दबाजी',
'खेलकुद, उद्यम, सुरक्षा, व्यापार',
'ठूलो लाभको सम्भावना, तर जोखिमपूर्ण निवेश',
'मित्रसँग ऊर्जावान सम्बन्ध, कहिलेकाहीँ विवाद',
'एकादशस्थो मङ्गलो लाभदो भवति',
'Phaladeepika',
'मंगलवार हनुमान मन्त्र जप र लाल मसूर दान।'),

(3,12,
'मंगल बाह्रौं भावमा खर्च र गुप्त शत्रुता ल्याउँछ। विदेश वास र अन्यायमा पैसा खर्च हुन सक्छ। निद्रा र आलस्यमा समस्या तर अनुशासित अभ्यासले मोक्षमार्ग बलियो बनाउँछ।',
'Mars in the twelfth brings expenditure and hidden enemies. Money may be spent on foreign stay and injustice. There is trouble with sleep and laziness though disciplined practice strengthens the path of liberation.',
'विदेश साहस, एकान्त अभ्यास, गुप्त शत्रु पराजय, मोक्ष बल',
'अनावश्यक खर्च, अनिद्रा, गुप्त विवाद, चोट',
'विदेशी संस्था, सुरक्षा, अस्पताल, अनुसन्धान',
'खर्च बढी, विदेशमा लगानी, बचत कम',
'परिवारबाट टाढा, गुप्त कडुवाइ',
'द्वादशस्थो मङ्गलो मोक्षहेतुकृत्',
'Saravali',
'मंगलवार हनुमान मन्त्र जप र मसूर दान गर्ने।');
