-- Seed : graha_bhava, house 10 (9 rows)
-- Run after seed_combo_bhava_a.sql

USE vedic_astrology_learn;

INSERT INTO graha_bhava (graha_id, bhava_id, interpretation_np, interpretation_en, positive_effects, challenges, career_indication, financial_indication, relationship_indication, classical_interpretation, sanskrit_reference, remedies) VALUES
(1,10,'सूर्य दसौं भावमा कर्म क्षेत्रमा उच्च पद दिने कारक हो। सरकार, प्रशासन र नेतृत्व क्षेत्रमा ख्याति प्राप्त हुन्छ।','Sun in the tenth is a strong factor for high position in career. Fame comes through government, administration and leadership.','पद, प्रतिष्ठा, अधिकार, सार्वजनिक सफलता','अहंकारले अधिनायकता, सहकर्मीसँग तनाव','राज्यसेवा, प्रशासन, शासन, शिक्षामा उच्च पद','नियमित आय र सरकारी स्रोतबाट लाभ','कर्म प्रधान हुँदा परिवारमा कम समय','सूर्यो दशमे राज्यप्रियो भवति','Brihat Parashara Hora Shastra, Adhyaya 19','रविवार सूर्यलाई जल अर्पण गर्ने।'),
(2,10,'चन्द्र दसौं भावमा सार्वजनिक लोकप्रियताबाट कर्ममा उन्नति दिन्छ। जनमानसमा चेहरा चिनिन्छ।','Moon in the tenth brings career progress through public popularity. The face becomes recognised among the masses.','लोकप्रियता, जनसेवा, सर्वोच्च पदसम्म पुग्ने','भावनामा उतारचढाव, काममा अस्थिरता','जनप्रतिनिधि, जनसञ्चार, खाद्य व्यवसाय','परिवर्तनशील तर पर्याप्त आय','काममा बढी समयले पारिवारिक तनाव','चन्द्रो दशमे जनप्रियो भवति','Brihat Parashara Hora Shastra, Adhyaya 19','सोमबार शिवलिंगमा जल चढाउने।'),
(3,10,'मङ्गल दसौं भावमा कर्म क्षेत्रमा ऊर्जा र पराक्रम दिन्छ। इन्जिनियरिङ र सुरक्षा क्षेत्रमा उन्नति हुन्छ।','Mars in the tenth gives energy and valour in career. There is progress in engineering and security fields.','पराक्रम, नेतृत्व, तक्निकी दक्षता, उच्च पद','अति आक्रामकता, सहकर्मीसँग झगडा','इन्जिनियरिङ, सेना, पुलिस, सुरक्षा, खनन','मेहनती आय, तर दुर्घटनाबाट हानि','काममा तलब बढी, पारिवारिक समय कम','मङ्गलो दशमे सेनापतिवत् कर्मिणम्','Brihat Parashara Hora Shastra, Adhyaya 19','मङ्गलबार हनुमान चालीसाको पाठ गर्ने।'),
(4,10,'बुध दसौं भावमा व्यापार, लेखन र प्रविधि क्षेत्रमा उन्नति दिन्छ। विश्लेषणात्मक काममा सफलता हुन्छ।','Mercury in the tenth brings progress in trade, writing and technology. There is success in analytical work.','बौद्धिक काम, व्यापार वृद्धि, बहुभाषिक दक्षता','अति महत्वाकांक्षा, द्विधा, धोका','लेखा, व्यापार, सञ्चार, कम्प्युटर विज्ञान','व्यापारबाट लाभ, परामर्शदाता आय','काममा मिलनसार, पारिवारिक समय सीमित','बुधो दशमे व्यापारप्रियो भवति','Brihat Parashara Hora Shastra, Adhyaya 19','बुधवार गायलाई हरियो घाँस खुवाउने।'),
(5,10,'गुरु दसौं भावमा उच्च शिक्षा र धर्म क्षेत्रमा उन्नति दिन्छ। शिक्षक, वकिल र धार्मिक नेताको रूपमा सफलता हुन्छ।','Jupiter in the tenth gives progress in higher education and dharma. There is success as a teacher, lawyer or religious leader.','ज्ञान क्षेत्रमा मान्यता, नैतिक नेतृत्व, उच्च पद','अति उदारताले आर्थिक कठिनाइ','शिक्षण, वकालत, धर्म, परामर्श','विद्याबाट आय, दान बढी','पारिवारिक मूल्य प्रधान जीवन','गुरुर्दशमे धर्मप्रियो भवति','Brihat Parashara Hora Shastra, Adhyaya 19','गुरुवार विष्णु मन्त्र जप्ने।'),
(6,10,'शुक्र दसौं भावमा कला र सौन्दर्य क्षेत्रमा उन्नति दिन्छ। डिजाइन, फेसन र मनोरञ्जनमा सफलता हुन्छ।','Venus in the tenth gives progress in art and beauty fields. There is success in design, fashion and entertainment.','कलात्मक कर्म, सम्मान, भौतिक सुख','काममा आलस्य, संयम कम','फेसन, डिजाइन, संगीत, आभूषण व्यवसाय','कलाबाट आय, भौतिक लाभ','पारिवारिक सुख कायम, तर काम बढी','शुक्रो दशमे विलासप्रियो भवति','Brihat Parashara Hora Shastra, Adhyaya 19','शुक्रबार दूध चढाउने।'),
(7,10,'शनि दसौं भावमा श्रम र अनुशासनबाट कर्ममा उन्नति दिन्छ। उच्च पद ढिलो तर दिगो हुन्छ।','Saturn in the tenth brings career progress through labour and discipline. High position comes late but is durable.','अनुशासन, दिगो स्थिरता, कठिन परिश्रमको फल','सानो उमेरमा असफलता, कठोरता','खनन, लोहा, यन्त्र, प्रशासन, सेवा','ढिलो तर स्थिर आय, बचतमा सफल','काममा कठोर, पारिवारमा जिम्मेवार','शनिर्दशमे कर्मप्रियो भवति','Brihat Parashara Hora Shastra, Adhyaya 19','शनिवार तिल तेल दान गर्ने।'),
(8,10,'राहु दसौं भावमा प्रविधि र विदेशी संस्थामा उन्नति दिन्छ। अचानक कर्म परिवर्तन सम्भव छ।','Rahu in the tenth gives progress in technology and foreign organisations. Sudden career change is possible.','प्रविधि दक्षता, विदेशी कम्पनीमा पद, अचानक उन्नति','अनिश्चितता, धोका, विवाद','आईटी, अन्तरिक्ष, प्रविधि, विदेशी कम्पनी','अचानक लाभ, तर अस्थायी','काममा उतारचढाव, पारिवारिक तनाव','राहुर्दशमे वैदेशिककर्मिणं भवति','Brihat Parashara Hora Shastra, Adhyaya 19','दुर्गा सप्तशतीको पाठ गर्ने।'),
(9,10,'केतु दसौं भावमा अनुसन्धान र आध्यात्मिक कर्ममा उन्नति दिन्छ। भौतिक पदभन्दा ज्ञानको मान्यता बढी हुन्छ।','Ketu in the tenth gives progress in research and spiritual work. Recognition comes for knowledge rather than material position.','अनुसन्धान क्षमता, गूढ ज्ञान, अचानक अवसर','पदमा अस्थिरता, भौतिक निराशा','अनुसन्धान, ज्योतिष, आध्यात्मिक शिक्षण','अनिश्चित आय, लाभमा उतारचढाव','काममा कम संलग्नता','केतुर्दशमे ज्ञानप्रियो भवति','Brihat Parashara Hora Shastra, Adhyaya 19','गणेश चालीसाको पाठ गर्ने।');
