-- =====================================================================
-- संयोजन विश्लेषण — complete Graha + Bhava Faladesh (part B)
-- Adds bhavas 2,3,4,5,6,8,9,11,12 for grahas 4-6 (Budha, Guru, Shukra).
-- Existing rows for bhavas 1,7,10 are kept (INSERT IGNORE is idempotent).
-- Content: structured knowledge data, written in own words.
-- =====================================================================

USE vedic_astrology_learn;

INSERT IGNORE INTO `graha_bhava` (`graha_id`,`bhava_id`,`interpretation_np`,`interpretation_en`,`positive_effects`,`challenges`,`career_indication`,`financial_indication`,`relationship_indication`,`classical_interpretation`,`sanskrit_reference`,`remedies`) VALUES

(4,2,
'बुध दोस्रो भावमा वाणी र धन दुवैमा चतुरता ल्याउँछ। व्यापार, लेखन र गणितबाट आय आउँछ। पैसा बचत गर्ने बुद्धि हुन्छ तर कहिलेकाहीँ एउटै ठाउँबाट धेरै स्रोत खोज्ने डरावट देखिन्छ।',
'Mercury in the second brings cleverness in both speech and wealth. Income comes through trade, writing and calculation. There is intelligence in saving money though sometimes anxiety arises from seeking many sources at once.',
'वाणी चतुरता, व्यापार बुद्धि, बचत क्षमता, लेखन कौशल',
'अति विश्लेषण, वाणीमा डरावट, पैसामा दोहोरो विचार',
'व्यापार, लेखन, लेखा, परामर्श',
'छोटो अवधिमा लाभ, तर बहुआयामिक आय',
'परिवारसँग बुद्धिमत्तापूर्ण व्यवहार',
'द्वितीयस्थो बुधो धनवान् भवति',
'Phaladeepika',
'बुधवार गणेश मन्त्र जप र हरित वस्त्र दान।'),

(4,3,
'बुध तेस्रो भावमा सञ्चार र लेखनमा प्रतिभा दिन्छ। छोटो यात्रामा व्यापारिक लाभ हुन्छ। भाइबहिनीसँग बुद्धिमत्ता साझेदारी रहन्छ तर कहिलेकाहीँ एकै कुरा दोहोर्याउने बानी लाग्छ।',
'Mercury in the third gives talent in communication and writing. Short journeys bring business benefit. There is an intellectual partnership with siblings though the habit of repeating the same point may sometimes develop.',
'सञ्चार कौशल, लेखन प्रतिभा, यात्रामा व्यापार, भाइबहिनी बुद्धि',
'अति बोल्ने बानी, दोहोरो कुरा, अधुरो विचार',
'पत्रकारिता, विपणन, अनुवाद, यात्रा व्यापार',
'छोटो यात्रा र सञ्चारबाट लाभ',
'भाइबहिनीसँग बौद्धिक आदानप्रदान',
'तृतीयस्थो बुधो वाक्पटु भवति',
'Brihat Jataka',
'बुधवार गणेश मन्त्र जप र दूर्वा अर्पण।'),

(4,4,
'बुध चौथो भावमा बौद्धिक सुख र शिक्षामा सफलता दिन्छ। घरमा पुस्तक र ज्ञानको वातावरण रहन्छ। वाहन र सम्पत्तिमा व्यावहारिकता रहन्छ तर मन एउटै ठाउँमा टिक्न नसक्ने हुन्छ।',
'Mercury in the fourth gives success in intellectual comforts and education. The home keeps an atmosphere of books and knowledge. There is practicality in vehicles and property though the mind may not settle in one place.',
'शिक्षा सुख, घरमा ज्ञान, व्यावहारिक सम्पत्ति, वाहन सुख',
'मन डोलने प्रवृत्ति, चिन्ता, घरमा अस्थिरता',
'शिक्षण, प्रकाशन, सल्लाह, भवन व्यवसाय',
'शिक्षा र लेखनबाट स्थिर आय',
'परिवारसँग बुद्धिमय सम्बन्ध',
'चतुर्थस्थो बुधो विद्यावान् भवति',
'Saravali',
'बुधवार गणेश मन्त्र जप र घरमा विद्या दीप प्रज्वलन।'),

(4,5,
'बुध पाँचौं भावमा तीव्र बुद्धि र शिक्षामा उत्कृष्टता दिन्छ। व्यापारमा अटकलबाजीबाट सोच-विचार गरेर लाभ हुन्छ। सन्तान बुद्धिमान हुन्छन् र विद्यार्थी जीवनमा ख्याति पाइन्छ।',
'Mercury in the fifth gives sharp intellect and excellence in education. Speculation in business brings gain when decided through careful thought. Children are intelligent and fame comes in student life.',
'तीव्र बुद्धि, शिक्षामा उत्कृष्टता, बुद्धिमान सन्तान, विश्लेषण क्षमता',
'अति विश्लेषण, निर्णयमा ढिलाइ, वादविवाद',
'शिक्षण, अनुसन्धान, व्यापार, सूचना प्रविधि',
'सोच-विचार गरी लगानीमा लाभ',
'सन्तान र शिष्यसँग बौद्धिक जडान',
'पञ्चमस्थो बुधो मेधावी भवति',
'Brihat Parashara Hora Shastra',
'बुधवार गणेश मन्त्र जप र विद्यार्थीलाई दान।'),

(4,6,
'बुध छैटौं भावमा बुद्धि र वाणीले शत्रुलाई परास्त गर्न सिकाउँछ। सेवा र व्यापारमा प्रतिष्ठा मिल्छ। तनाव र नसाको समस्या हुन सक्छ, तर समस्या समाधानमा निपुण हुन्छन्।',
'Mercury in the sixth teaches one to defeat enemies through intelligence and speech. Respect comes in service and trade. Nervous stress may occur though the person is skilled at solving problems.',
'शत्रु पराजय (बुद्धिले), सेवा प्रतिष्ठा, समस्या समाधान, व्यापार विजय',
'नसाको तनाव, अति चिन्ता, वाणी विवाद',
'लेखा, परामर्श, स्वास्थ्य सेवा, व्यापार',
'ऋण फिर्ता, व्यापारबाट नियमित आय',
'सहकर्मीसँग बुद्धिमत्ता व्यवहार',
'षष्ठस्थो बुधो रिपुं विजयति',
'Phaladeepika',
'बुधवार गणेश मन्त्र जप र हरित दान।'),

(4,8,
'बुध आउठौं भावमा अनुसन्धान र रहस्य ज्ञानमा गहिराइ दिन्छ। विरासत र लेखाजोखाबाट लाभ हुन सक्छ। नसा र मानसिक तनावमा सावधानी चाहिन्छ, तर जटिल कुरा बुझ्ने क्षमता असाधारण हुन्छ।',
'Mercury in the eighth gives depth in research and mysterious knowledge. Gain may come through inheritance and accounts. Care is needed for nerves and mental stress though the ability to understand complex matters is extraordinary.',
'अनुसन्धान क्षमता, रहस्य ज्ञान, लेखा कौशल, विरासत लाभ',
'नसाको तनाव, अचानक चिन्ता, गोपनीयता',
'अनुसन्धान, कर लेखा, प्रविधि, ज्योतिष',
'विरासत र छानबिनबाट लाभ, तर जोखिम पनि',
'गोपनीय सूचना र गम्भीर विचार',
'अष्टमस्थो बुधो गूढज्ञो भवति',
'Saravali',
'बुधवार गणेश मन्त्र जप र शिवलिङ्गमा जल।'),

(4,9,
'बुध नवौं भावमा ज्ञान र धर्मलाई जोड्छ। उच्च शिक्षा र अध्ययनमा सफलता मिल्छ। पिता वा गुरुबाट बौद्धिक सहयोग आउँछ र तीर्थ यात्रामा ज्ञान वृद्धि हुन्छ।',
'Mercury in the ninth links knowledge with dharma. Success comes in higher learning and study. Intellectual support arrives from father or teacher and wisdom grows on pilgrimage.',
'उच्च शिक्षा, ज्ञान वृद्धि, गुरु सहयोग, धर्म बुद्धि',
'धर्ममा शंका, अति विश्लेषण, गुरुसँग मतभेद',
'शिक्षण, अनुसन्धान, प्रकाशन, धर्म प्रचार',
'ज्ञानबाट दूरस्थ स्रोत, शिक्षामा लगानी',
'गुरु र पितासँग बौद्धिक सम्बन्ध',
'नवमस्थो बुधो धर्मज्ञो भवति',
'Brihat Jataka',
'बुधवार गणेश मन्त्र जप र गुरुलाई सम्मान।'),

(4,11,
'बुध एघारौं भावमा व्यापार र सञ्चारबाट लाभ दिन्छ। विस्तृत सम्पर्क जालले आय बढाउँछ। इच्छा पूरा हुन्छ तर धेरै कुरा एकैसाथ गर्ने चक्करमा केही अधुरो हुन सक्छ।',
'Mercury in the eleventh brings gains through trade and communication. A wide network of contacts increases income. Desires are fulfilled though taking on many things at once may leave some incomplete.',
'व्यापार लाभ, सम्पर्क जाल, इच्छा पूर्ति, लचिलो आय',
'अधुरो काम, अति फैलिएको ध्यान, अनिश्चितता',
'व्यापार, सञ्चार, मध्यस्थता, प्रविधि',
'सम्पर्क र व्यापारबाट बहुआयामिक लाभ',
'मित्रसँग बौद्धिक आदानप्रदान',
'एकादशस्थो बुधो लाभकृत् भवति',
'Phaladeepika',
'बुधवार गणेश मन्त्र जप र हरित वस्त्र दान।'),

(4,12,
'बुध बाह्रौं भावमा विदेशी व्यापार र गुप्त ज्ञानसँग जोडिन्छ। आयात-निर्यात र एकान्त अध्ययनबाट लाभ हुन्छ। खर्च बढ्छ तर हिसाब-किताबमा सतर्कताले बचत बच्छ।',
'Mercury in the twelfth connects with foreign trade and secret knowledge. Gain comes through import export and study in isolation. Expenses grow though caution in accounts preserves savings.',
'विदेशी व्यापार, गुप्त ज्ञान, एकान्त अध्ययन, बचत रक्षा',
'अनावश्यक खर्च, गोपनीयता, एकान्त तनाव',
'आयात-निर्यात, अनुवाद, अनुसन्धान, विदेश सेवा',
'विदेशबाट आय, तर खर्च पनि बढी',
'परिवारबाट टाढा बौद्धिक कार्य',
'द्वादशस्थो बुधो मोक्षबुद्धिप्रदः',
'Saravali',
'बुधवार गणेश मन्त्र जप र एकान्तमा अध्ययन।'),

(5,2,
'गुरु दोस्रो भावमा धन र समृद्धिको उदार कारक हुन्छ। शिक्षा र ज्ञानबाट आय आउँछ। परिवारमा सम्पन्नता र सद्भाव रहन्छ तर दानशीलताले कहिलेकाहीँ बचत कम हुन सक्छ।',
'Jupiter in the second is a generous significator of wealth and prosperity. Income comes through education and knowledge. Prosperity and harmony stay in the family though charity may sometimes reduce savings.',
'धन समृद्धि, ज्ञानबाट आय, पारिवारिक सद्भाव, उदारता',
'अति दानशीलता, बचत कम, आशावादमा अति',
'शिक्षण, परामर्श, धर्म, वित्त',
'शिक्षा र परामर्शबाट स्थिर सम्पत्ति',
'परिवारमा आदर र उदार सम्बन्ध',
'द्वितीयस्थो गुरुर्धनवान् भवति',
'Brihat Parashara Hora Shastra',
'गुरुवार विष्णु सहस्रनाम जप र पीले वस्त्र दान।'),

(5,3,
'गुरु तेस्रो भावमा धर्मप्रति साहस र लेखनमा प्रभाव दिन्छ। भाइबहिनी र साना भाइबाट सहयोग आउँछ। छोटो यात्रामा गुरु भेट हुन्छ र धार्मिक कार्यमा योगदान हुन्छ।',
'Jupiter in the third gives courage in dharma and influence in writing. Support comes from younger siblings. Short journeys bring meetings with teachers and contribution to religious works.',
'धर्म साहस, लेखन प्रभाव, भाइबहिनी सहयोग, यात्रामा गुरु भेट',
'अति विश्वास, आलस्य, दीर्घ वाक्य',
'लेखन, शिक्षण, धर्म प्रचार, परामर्श',
'लेखन र यात्राबाट लाभ',
'भाइबहिनी र गुरुसँग सद्भाव',
'तृतीयस्थो गुरुर्बलवान् भवति',
'Phaladeepika',
'गुरुवार विष्णु मन्त्र जप र पीले चामल दान।'),

(5,4,
'गुरु चौथो भावमा सुख र शान्तिको उदार कारक हुन्छ। सुन्दर घर, जग्गा र वाहन सुख मिल्छ। माताको आशीर्वाद रहन्छ र शिक्षामा सफलता पाइन्छ।',
'Jupiter in the fourth is a generous giver of happiness and peace. Comforts of a good home, land and vehicles are gained. The blessing of the mother remains and success comes in education.',
'घर सुख, जग्गा-वाहन, माताको आशीर्वाद, शिक्षा सफलता',
'अति आराम, घरमा विस्तारमा ढिलाइ, भारी खर्च',
'शिक्षण, भवन व्यवसाय, कृषि, परामर्श',
'जग्गा र घरबाट सम्पत्ति वृद्धि',
'परिवारमा सुख र आदर',
'चतुर्थस्थो गुरुर्सुखदो भवति',
'Brihat Jataka',
'गुरुवार विष्णु मन्त्र जप र घरमा तुलसी पूजा।'),

(5,5,
'गुरु पाँचौं भावमा अत्यन्त शुभ मानिन्छ। बुद्धि, सन्तान र पुण्यबाट सुख मिल्छ। शिक्षक वा विद्वान् बन्ने प्रवृत्ति रहन्छ र सट्टेबाजीमा पनि भाग्यले साथ दिन्छ।',
'Jupiter in the fifth is considered very auspicious. Happiness comes through intellect, children and merit. There is an inclination to become a teacher or scholar and fortune supports even in speculation.',
'बुद्धि, सन्तान सुख, पुण्य बल, शिक्षण प्रवृत्ति',
'अति आत्मविश्वास, सन्तानप्रति अपेक्षा, भर',
'शिक्षण, धर्म, लेखन, वित्त',
'भाग्यले लगानीमा लाभ, पुरानो सम्पत्ति वृद्धि',
'सन्तान र शिष्यसँग गहिरो स्नेह',
'पञ्चमस्थो गुरुर्मेधावी भवति',
'Saravali',
'गुरुवार विष्णु सहस्रनाम जप र विद्यार्थीलाई भोजन।'),

(5,6,
'गुरु छैटौं भावमा ज्ञानले शत्रुलाई शान्त गर्छ। सेवा र उपचारमा प्रतिष्ठा मिल्छ। शरीरमा चर्बी र जोर्नी सम्बन्धी समस्या हुन सक्छ तर उपायले सबै समाधान हुन्छ।',
'Jupiter in the sixth calms enemies through knowledge. Respect comes in service and healing. Problems related to fat and joints may occur though remedies bring solution to all.',
'शत्रु शान्ति, सेवा प्रतिष्ठा, उपचार कौशल, ऋण मुक्ति',
'शरीरमा चर्बी, जोर्नी दुखाइ, अति भोजन',
'चिकित्सा, सेवा, शिक्षण, प्रशासन',
'सेवाबाट नियमित आय, ऋण फिर्ता',
'शत्रुसँग सुलह र सेवाभाव',
'षष्ठस्थो गुरुर्रिपुं शमयति',
'Phaladeepika',
'गुरुवार विष्णु मन्त्र जप र पीले दान।'),

(5,8,
'गुरु आउठौं भावमा दीर्घायु र आध्यात्मिक ज्ञान दिन्छ। विरासत र अनुसन्धानबाट लाभ हुन्छ। जीवनका कठिनाइमा पनि भाग्यले रक्षा गर्छ र अन्ततः मार्गदर्शन मिल्छ।',
'Jupiter in the eighth gives longevity and spiritual knowledge. Gain comes through inheritance and research. Fortune protects even in life difficulties and guidance is ultimately received.',
'दीर्घायु, आध्यात्मिक ज्ञान, विरासत लाभ, भाग्य रक्षा',
'स्वास्थ्य जोखिम, विरासत ढिलाइ, रहस्य तनाव',
'अनुसन्धान, ज्योतिष, चिकित्सा, विरासत कार्य',
'विरासत र अनपेक्षित स्रोतबाट लाभ',
'गोपनीयता तर अन्ततः सत्य प्रकट',
'अष्टमस्थो गुरुरायुर्दायी भवति',
'Brihat Parashara Hora Shastra',
'गुरुवार विष्णु मन्त्र जप र आयुर्वेदिक सेवा।'),

(5,9,
'गुरु नवौं भावमा सर्वोत्तम फल दिन्छ। धर्म, भाग्य, पिता र गुरुको पूर्ण आशीर्वाद मिल्छ। उच्च शिक्षा, तीर्थ र आध्यात्मिक कार्यमा ख्याति फैलिन्छ।',
'Jupiter in the ninth gives the best results. Full blessings of dharma, fortune, father and teacher are gained. Fame spreads through higher learning, pilgrimage and spiritual works.',
'भाग्य बल, धर्म सिद्धि, गुरु-पिता आशीर्वाद, उच्च शिक्षा',
'भाग्यमा अति विश्वास, यात्रामा ढिलाइ, धर्ममा कठोरता',
'शिक्षण, धर्म प्रचार, न्याय, उच्च अधिकार',
'भाग्यले अप्रत्याशित सम्पत्ति, दानबाट वृद्धि',
'गुरु र पितासँग आदरपूर्ण सम्बन्ध',
'नवमस्थो गुरुर्भाग्यवान् भवति',
'Brihat Jataka',
'गुरुवार विष्णु सहस्रनाम जप र गुरु पूजा।'),

(5,11,
'गुरु एघारौं भावमा ठूलो लाभ र समृद्धिको कारक हुन्छ। इच्छा पूरा हुन्छ र प्रभावशाली मित्रहरू सहयोग गर्छन्। आय स्रोत बढ्छ तर दान र खर्चलाई सन्तुलन गर्नुपर्छ।',
'Jupiter in the eleventh is a significator of large gains and prosperity. Desires are fulfilled and influential friends extend support. Income sources grow though charity and spending need balance.',
'ठूलो लाभ, इच्छा पूर्ति, प्रभावशाली मित्र, आय वृद्धि',
'अति खर्च, आशावादमा अति, उधार दिने बानी',
'व्यापार, शिक्षण, परामर्श, धर्म',
'बहुआयामिक आय र निवेश लाभ',
'मित्र र परिवारसँग उदार सम्बन्ध',
'एकादशस्थो गुरुर्लाभदो भवति',
'Phaladeepika',
'गुरुवार विष्णु मन्त्र जप र ज्येष्ठ वृद्धलाई भोजन।'),

(5,12,
'गुरु बाह्रौं भावमा उदार खर्च र मोक्षमार्गलाई जोड्छ। धर्म र सेवामा खर्च हुन्छ जुन पुण्य बन्छ। विदेश वास र एकान्त ध्यानबाट शान्ति मिल्छ।',
'Jupiter in the twelfth links generous expenditure with the path of liberation. Spending on dharma and service becomes merit. Foreign stay and quiet meditation bring peace.',
'धर्ममा खर्च, पुण्य वृद्धि, विदेश वास, ध्यान शान्ति',
'अति खर्च, विश्राम कमता, विदेश ढिलाइ',
'विदेशी शिक्षा, धर्म संस्था, अस्पताल, अनुसन्धान',
'खर्च धर्ममा, तर पुण्यबाट पुनः लाभ',
'परिवारबाट टाढा तर आशीर्वाद रहने',
'द्वादशस्थो गुरुर्मोक्षप्रियो भवति',
'Saravali',
'गुरुवार विष्णु मन्त्र जप र अन्नदान।'),

(6,2,
'शुक्र दोस्रो भावमा कला र विलासिताबाट धन दिन्छ। मिठो वाणीले परिवारमा सुख ल्याउँछ। सौन्दर्य र भोग सम्बन्धी व्यवसायबाट आय आउँछ तर खर्च पनि उत्तिकै हुन्छ।',
'Venus in the second gives wealth through art and luxury. Sweet speech brings happiness in the family. Income comes from beauty and comfort related business though spending matches it.',
'धन लाभ, मिठो वाणी, कला सम्पन्नता, पारिवारिक सुख',
'अति विलासिता, खर्च बढी, भोगमा लिप्तता',
'कला, व्यापार, ब्युटी, मनोरञ्जन',
'कला र भोग सम्बन्धी सम्पत्ति वृद्धि',
'परिवारसँग मधुर सम्बन्ध',
'द्वितीयस्थो शुक्रो धनवान् भवति',
'Brihat Parashara Hora Shastra',
'शुक्रवार लक्ष्मी मन्त्र जप र श्वेत दान।'),

(6,3,
'शुक्र तेस्रो भावमा कलात्मक साहस र मनोरञ्जन कौशल दिन्छ। छोटो यात्रामा आनन्द र कलासँग जोडिन्छ। भाइबहिनीसँग सौहार्द रहन्छ तर आलस्यले काम ढिला गराउन सक्छ।',
'Venus in the third gives artistic courage and skill in entertainment. Short journeys bring joy and connection with art. Harmony remains with siblings though laziness may delay work.',
'कला साहस, मनोरञ्जन कौशल, यात्रा आनन्द, भाइबहिनी सौहार्द',
'आलस्य, अति भोग, काम ढिलाइ',
'कला, मनोरञ्जन, फेसन, पर्यटन',
'कला र यात्राबाट लाभ',
'भाइबहिनी र साथीसँग मिहिनेत',
'तृतीयस्थो शुक्रो हर्षवान् भवति',
'Phaladeepika',
'शुक्रवार लक्ष्मी मन्त्र जप र श्वेत वस्त्र दान।'),

(6,4,
'शुक्र चौथो भावमा सुन्दर घर र भव्य जीवन सुख दिन्छ। वाहन र कलात्मक सजावटमा रुचि रहन्छ। मातासँग स्नेह रहन्छ तर आराममा अति लिप्त हुन सक्छ।',
'Venus in the fourth gives the happiness of a beautiful home and grand living. Interest remains in vehicles and artistic decoration. Affection for the mother stays though one may become too attached to comfort.',
'सुन्दर घर, वाहन सुख, कला सजावट, माताको स्नेह',
'आराममा अति लिप्तता, घर खर्च बढी, आलस्य',
'भवन सजावट, फेसन, कला, आराम सेवा',
'घर र वाहनबाट सुख, कलाबाट आय',
'परिवारमा माया र सौन्दर्य',
'चतुर्थस्थो शुक्रो सुखदो भवति',
'Brihat Jataka',
'शुक्रवार लक्ष्मी पूजा र घरमा श्वेत दीप।'),

(6,5,
'शुक्र पाँचौं भावमा प्रेम, कला र सन्तान सुख दिन्छ। रचनात्मक बुद्धि र कलात्मक प्रतिभा फल्छ। प्रेम विवाह र सुन्दर सन्तानको सम्भावना रहन्छ, तर सट्टेबाजीमा सावधानी चाहिन्छ।',
'Venus in the fifth gives happiness of love, art and children. Creative intellect and artistic talent flourish. There is possibility of love marriage and beautiful children though caution is needed in speculation.',
'प्रेम सुख, कला प्रतिभा, सन्तान सौन्दर्य, सिर्जनात्मक बुद्धि',
'प्रेममा अति भावुकता, सट्टेबाजी जोखिम, भोगमा लिप्तता',
'कला, रचना, फेसन, प्रेम परामर्श',
'कलाबाट लाभ, प्रेम सम्बन्धी सम्पत्ति',
'प्रेम र सन्तानसँग मधुर सम्बन्ध',
'पञ्चमस्थो शुक्रो भोगवान् भवति',
'Saravali',
'शुक्रवार लक्ष्मी मन्त्र जप र कन्यालाई सुहाग सामग्री।'),

(6,6,
'शुक्र छैटौं भावमा चतुरता र आकर्षणले शत्रुलाई नियन्त्रण गर्छ। सेवा र मनोरञ्जन क्षेत्रमा प्रतिष्ठा मिल्छ। शरीरमा मधुमेह र मूत्र सम्बन्धी समस्या हुन सक्छ।',
'Venus in the sixth controls enemies through charm and cleverness. Respect comes in service and entertainment fields. Problems related to diabetes and urinary system may occur.',
'शत्रु नियन्त्रण, आकर्षण बल, सेवा प्रतिष्ठा, मोलभाव कौशल',
'मधुमेह, मूत्र समस्या, भोगमा अति, विवाद',
'मनोरञ्जन, सेवा, परामर्श, व्यापार',
'शत्रुलाई चतुरताले जित्ने, ऋण फिर्ता',
'शत्रुसँग आकर्षणबाट सुलह',
'षष्ठस्थो शुक्रो रिपुं जयति',
'Phaladeepika',
'शुक्रवार लक्ष्मी मन्त्र जप र तिल दान।'),

(6,8,
'शुक्र आउठौं भावमा विरासत र गुप्त कलाबाट लाभ दिन्छ। जीवनसाथीको सम्पत्ति वा साझेदारीबाट आय हुन सक्छ। अचानक भोगमा परिवर्तन र स्वास्थ्य सम्बन्धी सावधानी चाहिन्छ।',
'Venus in the eighth gives gain through inheritance and hidden arts. Income may arrive from spouse property or partnership. Sudden changes in comforts and caution in health are indicated.',
'विरासत लाभ, गुप्त कला, साझेदारी आय, अन्तर्दृष्टि',
'अचानक भोग परिवर्तन, स्वास्थ्य जोखिम, गोपनीयता',
'कला अनुसन्धान, बीमा, विरासत कार्य, परामर्श',
'विरासत र साझेदारीबाट अनपेक्षित लाभ',
'जीवनसाथीसँग गहिराइ र गोपनीयता',
'अष्टमस्थो शुक्रो भोगदो भवति',
'Brihat Parashara Hora Shastra',
'शुक्रवार लक्ष्मी मन्त्र जप र श्वेत फल दान।'),

(6,9,
'शुक्र नवौं भावमा भाग्य र कलाबाट सुख दिन्छ। धार्मिक कार्यमा सौन्दर्य र कला योगदान हुन्छ। पिता र गुरुबाट सहयोग र तीर्थ यात्रामा आनन्द मिल्छ।',
'Venus in the ninth gives happiness through fortune and art. Beauty and art contribute to religious works. Support comes from father and teacher and joy is found on pilgrimage.',
'भाग्य सुख, कला धर्म, गुरु-पिता सहयोग, तीर्थ आनन्द',
'भाग्यमा अति निर्भरता, धर्ममा आराम, यात्रा ढिलाइ',
'कला शिक्षण, धर्म कार्य, पर्यटन, रचनात्मक उद्योग',
'भाग्यले कलाबाट लाभ, दानबाट वृद्धि',
'पिता-गुरुसँग स्नेहपूर्ण सम्बन्ध',
'नवमस्थो शुक्रो भाग्यवान् भवति',
'Brihat Jataka',
'शुक्रवार लक्ष्मी मन्त्र जप र गुरु पूजा।'),

(6,11,
'शुक्र एघारौं भावमा कला र सम्बन्धबाट लाभ दिन्छ। सामाजिक जालबाट आय आउँछ र इच्छा पूरा हुन्छ। सुन्दर र प्रभावशाली मित्रहरू सहयोग गर्छन् तर अति भोगमा खर्च हुन सक्छ।',
'Venus in the eleventh brings gains through art and relationships. Income arrives through social networks and desires are fulfilled. Beautiful and influential friends help though excess indulgence may increase spending.',
'लाभ, सामाजिक जाल, इच्छा पूर्ति, प्रभावशाली मित्र',
'अति भोग, खर्च बढी, मित्रमा निर्भरता',
'कला, व्यापार, मनोरञ्जन, सामाजिक कार्य',
'सम्बन्ध र कलाबाट बहुआयामिक लाभ',
'मित्र र परिवारसँग मिहिनेत',
'एकादशस्थो शुक्रो लाभकृत् भवति',
'Phaladeepika',
'शुक्रवार लक्ष्मी मन्त्र जप र मिठाई दान।'),

(6,12,
'शुक्र बाह्रौं भावमा विलासिता र विदेशसँग जोडिन्छ। सुख-सुविधामा खर्च र विदेशमा प्रेम सम्बन्ध हुन सक्छ। एकान्तमा कला अभ्यासबाट शान्ति र मोक्षमार्ग प्रबल हुन्छ।',
'Venus in the twelfth connects with luxury and foreign lands. Spending grows on comforts and love relations may form abroad. Practice of art in isolation brings peace and the path of liberation strengthens.',
'विदेश वास, कला एकान्त, भोग शान्ति, मोक्ष मार्ग',
'अनावश्यक खर्च, प्रेम विवाद, आलस्य, अनिद्रा',
'विदेशी कला, मनोरञ्जन, अस्पताल, एकान्त अभ्यास',
'विदेशबाट लाभ तर खर्च पनि बढी',
'परिवारबाट टाढा प्रेम सम्बन्ध',
'द्वादशस्थो शुक्रो मोक्षभोगप्रदः',
'Saravali',
'शुक्रवार लक्ष्मी मन्त्र जप र एकान्त कला अभ्यास।');
