-- Seed : graha_bhava, houses 1 and 7  (18 rows)
-- Run after schema.sql + seed_topics.sql + seed_grahas.sql + seed_rashis.sql

USE vedic_astrology_learn;

INSERT INTO graha_bhava (graha_id, bhava_id, interpretation_np, interpretation_en, positive_effects, challenges, career_indication, financial_indication, relationship_indication, classical_interpretation, sanskrit_reference, remedies) VALUES
(1,1,'सूर्य लग्नमा रहँदा व्यक्ति आत्मविश्वासी र नेतृत्वमा सक्षम हुन्छ। शारीरिक रूप बलियो र ऊर्ध्वाधर हुन्छ। आफ्नो अधिकारमा विश्वास गर्ने प्रकृति देखिन्छ।','Sun in the first house makes the native confident and capable of leadership. The physique is strong and upright. There is natural trust in own authority.','आत्मविश्वास, नेतृत्व गुण, सार्वजनिक सम्मान, ऊर्जावान शरीर','अहंकार, आलोचनामा असहिष्णुता, स्वास्थ्यमा ताप','राज्य, प्रशासन, शिक्षा र नेतृत्व क्षेत्रमा उन्नति','सरकारी स्रोतबाट लाभ, सम्पत्तिमा वृद्धि','आफ्नो अहम्ले जीवनसाथीसँग द्वन्द्व सिर्जना गर्न सक्छ','सूर्यो लग्नस्थो बलवान् भवति','Brihat Parashara Hora Shastra, Adhyaya 2','रविवार जल अर्पण र सूर्य मन्त्र जप।'),
(1,7,'सूर्य सप्तम भावमा वैवाहिक जीवनमा अहम् कारक हुन्छ। जीवनसाथीसँग आत्ममहत्वको टकराव हुन्छ तर जीवनसाथी बलिया र प्रतिष्ठित हुन्छन्।','Sun in the seventh makes ego a factor in married life. There can be clashes of self-importance with the spouse, though the partner is strong and dignified.','जीवनसाथीको प्रतिष्ठा, साझेदारीमा अधिकार, सार्वजनिक मान्यता','अहम् टकराव, विवाद, साझेदारीमा द्वन्द्व','सरकारी वा उच्च पदको जीवनसाथी, व्यापारमा स्थापना','साझेदारीबाट आय, तर विवादले हानि पनि','विवाहमा ढिला वा विवाद पछि सामञ्जस्य','सप्तमस्थः सूर्यो द्वन्द्वावहः','Brihat Parashara Hora Shastra, Adhyaya 12','शनिवार तिल तेल दान र सूर्य मन्त्र जप।'),
(2,1,'चन्द्र लग्नमा व्यक्ति संवेदनशील, कलात्मक र लोकप्रिय हुन्छ। चेहरा गोलाकार र आँखा आकर्षक हुन्छन्। मन भावनाप्रधान हुन्छ।','Moon in the first makes the native sensitive, artistic and popular. The face is round and the eyes attractive. The mind is emotionally driven.','चाक्षुष आकर्षण, लोकप्रियता, कलात्मक प्रतिभा, मातृ स्नेह','मन चञ्चलता, भावनामा अस्थिरता, निर्णय ढिला','कला, सञ्चार, जनसम्पर्क, खाद्य उद्योग','जल र पर्यटनबाट लाभ, परिवर्तनशील आय','भावनात्मक जीवनसाथी, माया गहिरो','चन्द्रो लग्ने सौम्यवद् भवति','Brihat Parashara Hora Shastra, Adhyaya 3','सोमबार शिवलिंगमा जल चढाउने।'),
(2,7,'चन्द्र सप्तम भावमा भावनात्मक जीवनसाथी र सुखद वैवाहिक जीवन दिन्छ। जीवनसाथी दयालु र सहयोगी हुन्छन्।','Moon in the seventh gives an emotional spouse and a pleasant married life. The partner is compassionate and supportive.','सुखद विवाह, सहयोगी जीवनसाथी, जनसम्पर्क लाभ','भावनामा अस्थिरता, अनावश्यक चिन्ता','साझेदारी व्यवसाय, सेवा क्षेत्र','जीवनसाथीको आयबाट लाभ','विवाह सुखद तर मन अस्थिर','सप्तमे चन्द्रो मातृवत् स्नेहं ददाति','Brihat Parashara Hora Shastra, Adhyaya 12','सोमबार दूध चढाउने र चन्द्र मन्त्र जप।'),
(3,1,'मङ्गल लग्नमा अत्यन्त साहसी र शारीरिक रूपमा बलियो बनाउँछ। प्रतिस्पर्धामा अग्रणी, तर क्रोध पनि बढी हुन्छ।','Mars in the first makes the native extremely courageous and physically strong. They lead in competition, though anger can also be high.','साहस, ऊर्जा, पराक्रम, प्रतिस्पर्धामा जित','क्रोध, चोट, दुर्घटना, विवाद','सेना, पुलिस, खेलकुद, इन्जिनियरिङ','भूमि र निर्माणबाट लाभ, तर विवादले हानि','अत्यधिक क्रोधले सम्बन्धमा तनाव','मङ्गलो लग्ने वीर्यवान् भवति','Brihat Parashara Hora Shastra, Adhyaya 6','मङ्गलबार हनुमान चालीसाको पाठ गर्ने।'),
(3,7,'मङ्गल सप्तम भावमा वैवाहिक जीवनमा चुनौती ल्याउँछ। जीवनसाथीसँग प्रायः मतभेद हुन्छ तर जीवनसाथी ऊर्जावान हुन्छन्।','Mars in the seventh brings challenges in married life. There are often disagreements with the spouse, though the partner is energetic.','जीवनसाथीको पराक्रम, स्वतन्त्र सोच, निर्णायकता','मतभेद, शीघ्र विवाद, माङ्गलिक पीडा','सुरक्षा, इन्जिनियरिङ, स्वतन्त्र व्यवसाय','स्वतन्त्र आय तर खर्च बढी','विवाद, तर शारीरिक आकर्षण बलियो','सप्तमस्थो मङ्गलो विवादं कुर्यात्','Brihat Parashara Hora Shastra, Adhyaya 12','मङ्गलबार शिवलिंगमा दूध चढाउने र रुद्राभिषेक।'),
(4,1,'बुध लग्नमा बुद्धिमान, सञ्चारमा दक्ष र चतुर बनाउँछ। तर्कशक्ति र शिक्षाप्रिय स्वभाव हुन्छ।','Mercury in the first makes the native intelligent, skilled in communication and clever. There is reasoning ability and love of learning.','बुद्धिमत्ता, वाणी कला, व्यापारिक चतुराई, शिक्षा','द्विधा, अति चिन्ता, शंकाग्रस्त मन','व्यापार, लेखन, शिक्षण, प्राविधिक काम','व्यापारबाट नियमित आय','संवाद क्षमताले सम्बन्ध सुधार','बुधो लग्ने वाक्पटुतां ददाति','Brihat Parashara Hora Shastra, Adhyaya 10','बुधवार गायलाई हरियो घाँस खुवाउने।'),
(4,7,'बुध सप्तम भावमा बुद्धिमान र संवादप्रिय जीवनसाथी दिन्छ। विवाहमा सामञ्जस्य र सहभागिता हुन्छ।','Mercury in the seventh gives an intelligent and communicative spouse. There is cooperation and partnership in marriage.','बुद्धिमान जीवनसाथी, संवाद सुधार, साझेदारीमा लाभ','शंका, अनावश्यक तर्क, भावना कम','व्यापारिक साझेदारी, सल्लाहकार काम','साझेदारीबाट लाभ','सामञ्जस्यपूर्ण तर कहिलेकाहीं अलगाव','सप्तमे बुधो मित्रवत् स्वामीं ददाति','Brihat Parashara Hora Shastra, Adhyaya 12','बुधवार गणेशलाई दूर्वा चढाउने।'),
(5,1,'गुरु लग्नमा व्यक्ति ज्ञानी, उदार र आध्यात्मिक प्रवृत्तिको हुन्छ। सम्मानित र दीर्घायु हुन्छन्।','Jupiter in the first makes the native wise, generous and spiritually inclined. They are respected and long-lived.','ज्ञान, सम्मान, दीर्घायु, उदारता','अति आशावाद, वसा बढ्ने समस्या','शिक्षण, धर्म, कानून, परामर्श','लाभदायक आय, तर अति खर्चीलो','सम्मानित जीवनसाथी, परिवार प्रिय','गुरुर्लग्ने ज्ञानवान् भवति','Brihat Parashara Hora Shastra, Adhyaya 11','गुरुवार गायलाई चना खुवाउने।'),
(5,7,'गुरु सप्तम भावमा भाग्यवान जीवनसाथी र सुखद विवाह दिन्छ। जीवनसाथी ज्ञानी र धार्मिक हुन्छन्।','Jupiter in the seventh gives a fortunate spouse and a happy marriage. The partner is learned and religious.','भाग्यवान जीवनसाथी, शुभ विवाह, पारिवारिक सुख','अति विश्वासले धोका, उमेर फरक','विधि, शिक्षा, सामाजिक सेवा','जीवनसाथीको सम्पत्तिबाट लाभ','सुखद विवाह, शुभ सन्तान','सप्तमे गुरुः शुभविवाहं ददाति','Brihat Parashara Hora Shastra, Adhyaya 12','गुरुवार पीलो वस्त्र लगाउने।'),
(6,1,'शुक्र लग्नमा व्यक्ति सुन्दर, आकर्षक र कलात्मक हुन्छ। विलासिता र भोगप्रिय स्वभाव देखिन्छ।','Venus in the first makes the native beautiful, attractive and artistic. There is a love of comfort and enjoyment.','सौन्दर्य, कला, आकर्षण, सामाजिक लोकप्रियता','अति भोगविलास, आलस्य','कला, संगीत, फेसन, डिजाइन','भौतिक सुख र धन प्राप्ति','प्रेममा सफल, जीवनसाथी आकर्षक','शुक्रो लग्ने रूपवान् भवति','Brihat Parashara Hora Shastra, Adhyaya 13','शुक्रबार शिवलिंगमा दूध चढाउने।'),
(6,7,'शुक्र सप्तम भावमा स्वयं वैवाहिक भावमा रहँदा अत्यन्त शुभ वैवाहिक सुख दिन्छ। जीवनसाथी सुन्दर र सहयोगी हुन्छन्।','Venus in its own seventh house gives highly auspicious marital happiness. The spouse is attractive and cooperative.','उत्तम जीवनसाथी, वैवाहिक सुख, कलात्मक साझेदारी','सान्द्रता, संयम कम','कला, मनोरञ्जन, विवाह सल्लाह','जीवनसाथीको धनबाट लाभ','सुखद विवाह, प्रेम विवाह','स्वगृहे शुक्रो विवाहे शुभाकरी','Brihat Parashara Hora Shastra, Adhyaya 12','शुक्रबार लक्ष्मी मन्त्र जप्ने।'),
(7,1,'शनि लग्नमा व्यक्ति अनुशासित, धैर्यवान र गम्भीर हुन्छ। सानो उमेरमा कठिनाइ तर पछि ठूलो उन्नति हुन्छ।','Saturn in the first makes the native disciplined, patient and serious. There is hardship in early life but great progress later.','धैर्य, अनुशासन, दृढ संकल्प, दीर्घायु','सानो उमेरमा कठिनाइ, अवसाद, हड्डी पीडा','खनन, लोहा, कृषि, प्रशासन','ढिलो तर स्थिर आय','विवाहमा ढिला, जीवनसाथी वयोवृद्ध','शनिर्लग्ने कर्तव्यपरायणः भवति','Brihat Parashara Hora Shastra, Adhyaya 15','शनिवार शनि मन्त्र जप्ने र तिल तेल दान।'),
(7,7,'शनि सप्तम भावमा विवाहमा ढिला र जीवनसाथीसँग उमेर फरक हुन्छ। सम्बन्धमा जिम्मेवारी र अनुशासन देखिन्छ।','Saturn in the seventh delays marriage and there can be an age gap with the spouse. There is responsibility and discipline in the relationship.','दीर्घकालीन स्थिर सम्बन्ध, जिम्मेवार जीवनसाथी','विवाहमा ढिला, भावना कम, दूरी','साझेदारी, सेवा, कृषि व्यवसाय','दीर्घकालीन बचत, अनुशासित व्यवस्थापन','विवाह ढिलो तर टिकाउ','सप्तमे शनिर्विलम्बेन विवाहं कुर्यात्','Brihat Parashara Hora Shastra, Adhyaya 12','शनिवार शनि मन्त्र जप्ने।'),
(8,1,'राहु लग्नमा अपरम्परागत र विदेशसँग सम्बन्धित व्यक्तित्व दिन्छ। भौतिक उन्नति छ तर भ्रम पनि छ।','Rahu in the first gives an unconventional personality linked to foreign matters. There is material progress but also illusion.','विदेश सम्बन्ध, प्रविधि ज्ञान, अचानक उन्नति','भ्रम, अन्धविश्वास, चोट','प्रविधि, अन्तरिक्ष, विदेशी कम्पनी','अचानक लाभ, तर अस्थिर','अपरम्परागत जीवनसाथी, विदेशी सम्बन्ध','राहुर्लग्ने विचित्रवत् चरित्रं कुर्यात्','Brihat Parashara Hora Shastra, Adhyaya 17','दुर्गा सप्तशतीको पाठ गर्ने।'),
(8,7,'राहु सप्तम भावमा असामान्य वा विदेशी जीवनसाथी दिन्छ। विवाहमा अप्रत्याशित परिस्थिति आउँछ।','Rahu in the seventh gives an unusual or foreign spouse. Unexpected circumstances arise in marriage.','विदेशी जीवनसाथी, सामाजिक मान्यता, अचानक विवाह','अविश्वास, गोपनीय समस्या','विदेश व्यापार, प्रविधि, अनुसन्धान','विदेशबाट अचानक लाभ','सम्बन्धमा रहस्य र उतारचढाव','सप्तमे राहुर्विदेशवधूं ददाति','Brihat Parashara Hora Shastra, Adhyaya 12','दुर्गा सप्तशती र गणेश चालीसाको पाठ।'),
(9,1,'केतु लग्नमा व्यक्ति आध्यात्मिक र वैराग्यप्रिय हुन्छ। भौतिक कुरामा कम रुचि तर गूढ ज्ञानमा बढी।','Ketu in the first makes the native spiritual and detached. Less interest in material life but more in occult knowledge.','आध्यात्मिक शक्ति, गूढ ज्ञान, अचानक ज्ञान','भ्रम, असमञ्जस, एकान्तवास','अनुसन्धान, ज्योतिष, आध्यात्मिक कार्य','लाभमा अनिश्चितता, भौतिक कमी','भावनात्मक दूरी, एकान्त प्रवृत्ति','केतुर्लग्ने वैराग्यवान् भवति','Brihat Parashara Hora Shastra, Adhyaya 18','गणेश चालीसाको पाठ गर्ने।'),
(9,7,'केतु सप्तम भावमा वैवाहिक सम्बन्धमा आध्यात्मिक झुकाव र भावनात्मक दूरी ल्याउँछ। भौतिक सम्बन्धभन्दा आध्यात्मिक साथी माग्छ।','Ketu in the seventh brings spiritual inclination and emotional distance in marriage. There is a search for a spiritual partner more than a physical one.','आध्यात्मिक साथी, गहिरो समझ, वैराग्य','भावनात्मक दूरी, अलगाव, विवाद','आध्यात्मिक सेवा, अनुसन्धान','अनिश्चित लाभ, भौतिक कमी','सम्बन्धमा कमी, विछोड','सप्तमे केतुर्विरक्तिं ददाति','Brihat Parashara Hora Shastra, Adhyaya 12','गणेश चालीसा र दुर्गा सप्तशती पाठ।');
